### ISSUE TITLE
DELETE on a versioned item should (probably optionally) not delete archived versions.

### ISSUE THREAD

**Issue by mikenerone** [nicolaiarocci/eve#335]
In my app, the reason I'm wanting to keep versioned documents in the first place is for auditing purposes. Without going into too much detail, events occur in our system, and we process those events according to a constantly-evolving set of rules that are defined in a MongoDB collection that is managed via an Eve API (if I have my wish). "Evolving" means that individual rules are frequently updated but also occasionally DELETED. When a rule is applied to an event, we record it (e.g. "Rule X, version N, was applied.") Later, if anything erroneous is found to have happened, we can go look at exactly how the rule was defined at the time. This currently breaks with DELETE, though, because deletion results in removal of the archived versions of the document, as well.

The workaround I currently have in mind is to basically have a `deleted` boolean field, and filter them out by default for that resource. This is clunky because it means that deletion would be done with PATCH/PUT and it just leaves the primary collection cluttered. IMO, there needs to be a way to support DELETE on the resource items while still preserving the auditability.

The behavior I would expect is that if item X is deleted, `/resource/X` would result in a 404, but that `/resource/X?version=N` would still work. Clearly, though, there's plenty of room for interpretation as to what the right semantics would be, so I haven't done any work on this. I'm just throwing it up here for consideration for the time being.

**Comment by nicolaiarocci** [comment]
#626 is a pull request by @nckpark that tries to address concerns expressed in this thread. It's big and it's feature rich so I would appreciate your feedback in the PR thread, if you are still interested in this feature. Thanks!
