### ISSUE TITLE
Mongo DBRef handling

### ISSUE THREAD

**Issue by bogklug** [nicolaiarocci/eve#434]
I am trying to use EVE to serve a database created with mongoengine (http://mongoengine.org/). Mongoengine uses DBRefs (http://docs.mongodb.org/manual/reference/database-references/#dbref) to implemenent GenericReferenceFields (http://docs.mongoengine.org/apireference.html#mongoengine.fields.GenericReferenceField) and EVE (version 0.4) raises a "DBRef(u'a-collection', ObjectId('53f9fda4e555c0730bba864e')) is not JSON serializable" exception when serving a document containing a DBRef.

**Comment by nicolaiarocci** [comment]
FYI DBRef support has been just merged https://github.com/nicolaiarocci/eve/commit/28ef48e336ced4b8210fc9c7228f2187713860ee
