### ISSUE TITLE
sqlalchemy branch can not post numeric type through multipart/form-data Content-Type 

### ISSUE THREAD

**Issue by copuzzle** [nicolaiarocci/eve#514]
I am working on sqlalchemy branch.
model:
    
    class Invoices(CommonColumns):
        __tablename__ = 'invoices'
        id = Column(Integer, primary_key=True, autoincrement=True)
        number = Column(Integer)
        people_id = Column(Integer, ForeignKey(People.id))
        people = relationship('People', uselist=False)
    

and when post data through form-data,it response

    {
    "_status": "ERR",
    "_issues": {
        "number": "must be of integer type"
    },
    "_error": {
        "message": "Insertion failure: 1 document(s) contain(s) error(s)",
        "code": 422
    }
        }

**Comment by nicolaiarocci** [comment]
There's now a eve-sqlalchemy extension available. If this ticket is still relevant pleast re-open it over there: https://github.com/RedTurtle/eve-sqlalchemy
