### ISSUE TITLE
Support for boolean operations in hook lookup dictionaries with sql alchemy

### ISSUE THREAD

**Issue by Leonidaz0r** [nicolaiarocci/eve#528]
When using MongoDB it is possible to apply boolean operations in filters using the lookup parameter of hooks.
The lookup parameter is parsed using parse_dictionary in eve/io/sql/parser.py, which seems not to support anything but equal comparison with AND.
I would like to be able to add a filter including an OR in a pre_GET hook, which does not seem possible at the moment.

One solution I could see is to add support for more operators to parse_dictionary to support more complex mongo queries. Another possibility would be to change the parameters of hooks to be able to use the python syntax, which would somehow be more logical as the SQLAlchemy branch should not depend on MongoDB knowledge.

**Comment by nicolaiarocci** [comment]
There's now a eve-sqlalchemy extension available. If this ticket is still relevant pleast re-open it over there: https://github.com/RedTurtle/eve-sqlalchemy
