### ISSUE TITLE
Bulk updates

### ISSUE THREAD

**Issue by msbrogli** [nicolaiarocci/eve#538]
I'm using python-eve for the first time and I'm not sure whether bulk updates are available or not. My problem is that I need to import a long list of products and it is a very slow operation due to the number of requests. First I need to do a GET in order to check whether the product already exists or not. Then, I need to do a POST or PATCH. More than 99% of the cases, I do a GET and a PATCH.
How do I improve the performance of it? Is there a bulk update?

**Comment by nicolaiarocci** [comment]
Assuming that you already have the unique id for every document, you could be optimistic about it and attempt a PATCH beforehand. Only when it fails you fallback to a POST request. Since 99% are PATCH, you should get a drastic performance boost. 

Bulk inserts (POST) are supported but PATCH is a document operation so no bulks allowed there.

**Comment by msbrogli** [comment]
Actually I can't, since I need the etag and the _id beforehand. I only have the additional lookup value.

**Comment by nicolaiarocci** [comment]
You may opt to disable ETAG matching, see [Disabling Concurrency Control][http://python-eve.org/features.html#disabling-concurrency-control].

**Comment by sapamja** [comment]
So, if we disable concurrency control, then we much have to provide the id in the url.

**Comment by nicolaiarocci** [comment]
On PATCH? Yes otherwise the system does not know what to update. Not needed on POST (actually it should not be there in that case, Mongo will return the new document id for you).

**Comment by sapamja** [comment]
Yes on Patch, Is there any chance of supporting bulk patch request in future.

**Comment by nicolaiarocci** [comment]
Not planned at the moment, I am afraid.
