### ISSUE TITLE
If-Modified-Since fails when a document is deleted and the resource is not empty

### ISSUE THREAD

**Issue by msbrogli** [nicolaiarocci/eve#539]
To replicate this behavior:

1. Create a resource and add a bunch of documents
2. Do a GET on the resource list endpoint
3. Do a DELETE on one of the documents
4. Do a GET on the resource list endpoint

On step 4, you will receive a 304 Not modified.

This issue is related to #243.

**Comment by msbrogli** [comment]
I'm thinking how to handle this issue. A not-so-good way would be to create a new collection that would store the last date of delete in the other collections. Another way would be to create a sentinel document in the collections. This sentinal would never be returned but it would be updated when any other document is deleted.

**Comment by msbrogli** [comment]
If anyone is having problems with this issue, I'm using the following workaround to keep my app running. It just removes the If-Modified-Since header before processing the request.

```python
def pre_GET(resource, request, lookup):
    if request.if_modified_since:
        request.if_modified_since = None
    request.headers.environ.pop('HTTP_IF_MODIFIED_SINCE', None)
app.on_pre_GET += pre_GET
```

**Comment by nicolaiarocci** [comment]
See #334: in 0.5 IMS has been removed from collection endpoint (you can still get the same feature by requesting with a `?where={"_updated"; ...}`). The [OpLog](http://python-eve.org/features#operations-log) has been also added, which can be used to retrieve what has been deleted (also see [this post](http://nicolaiarocci.com/feature-overview-the-eve-oplog/) on my blog which predates the oplog release)
