### ISSUE TITLE
Required version of Cerberus

### ISSUE THREAD

**Issue by girogiro** [nicolaiarocci/eve#542]
Would be possible to set the required version of Cerberus to 0.8 for Eve 0.5? There are some fixes since Cerb 0.7.2 that is required by Eve now and Cerb must be updated separately after Eve installation to get those fixes.

**Comment by nicolaiarocci** [comment]
Yes it's planned. Actually, it's already on the [0.5 branch](https://github.com/nicolaiarocci/eve/tree/0.5) which is going to be merged early next week when I release v0.5.
