### ISSUE TITLE
Pagination global settings

### ISSUE THREAD

**Issue by kapouille** [nicolaiarocci/eve#544]
I found myself in a situation when I have 2 clients that need to retrieve results. One needs pagination, the other doesn't (and would rather not carry the burden of it).

However, it appears that when the ``PAGINATION`` setting is set to ``False``, all features of pagination are enforceably disabled, even when ``max_results`` and ``page`` url params are specified:
 - ``max_results`` simply limits the number of records returned.
 - ``page`` is silently ignored.
This is slightly confusing as it appears that pagination is supported when the user asks for it.

I would have thought that the behaviour was something like this:
  - ``PAGINATION = True`` (default): all GET requests are paginated.
  - ``PAGINATION = False``: GET requests aren't paginated by default, but if ``max_results`` and/or ``page`` parameters are provided, Eve will returned paginated results.

Is there a reason why when ``PAGINATION`` is set to ``False``, it is enforced not to work? I'd be happy to contribute a patch to make it behave like proposed above.

**Comment by nicolaiarocci** [comment]
I think that the whole idea of setting `PAGINATION = False` was that the maintainer does not want to allow pagination, be it initiated by client or not (say you have performance concerns for example). Not sure if allowing a client-initiated pagination would be appropriate for most use cases really. 

Maybe there could be a new dedicated setting, something like `PAGINATION_ALLOW_CLIENT_INITIATED` boolean... it could follow `PAGINATION` by default, but could be explicitly enabled in cases like yours. Overall it looks a bit overcomplicated to me. 

Thoughts?

**Comment by kapouille** [comment]
Well, I thought it made sense it would behave as an optional thing by default, but if it's not, it's quite alright.
Looking through the code, I understand why from a code perspective it is how it works. 
However, I'm going to close the issue as there's no capital need for it and adding yet another configuration tag is going to muddle things up.

Thanks!

**Comment by DavidTWco** [comment]
I've just found this issue as I was experiencing a similar issue, I wanted to be able to use the `max_results` functionality without a limit. Configuring Eve as follows allowed me to still use the pagination functionality without having any practical limits.

```python
PAGINATION_LIMIT = float('inf')
PAGINATION_DEFAULT = float('inf')
```

**Comment by nicolaiarocci** [comment]
Nice :+1: .
