### ISSUE TITLE
Dependecies with value checking seems broken

### ISSUE THREAD

**Issue by oyvhanse** [nicolaiarocci/eve#547]
I'm trying out dependencies according to the example on:
http://cerberus.readthedocs.org/en/latest/#dependencies

It works fine when using the cerberus validator directly (as the example does).
But when I try the same through eve, then I can post objects that should have been rejected.

Example app:
```python
schema = {'field1': {'required': False}, 'field2': {'required': True, 'dependencies': {'field1': ['one', 'two']}}}

my_settings = {
    'RESOURCE_METHODS': ['GET', 'POST', 'DELETE'],
    'ITEM_METHODS': ['GET', 'PATCH', 'PUT', 'DELETE'],
    'DOMAIN': {
        'posts': {
            'schema': schema
        }
    }
}

from eve import Eve
app = Eve(settings=my_settings)
app.run()
```

Example post, that should have been rejected:
{"field1": "three", "field2": 7}

Without value checking works fine.

**Comment by nicolaiarocci** [comment]
Thanks should be fixed now.

**Comment by oyvhanse** [comment]
Super... thanks for the quick response
