### ISSUE TITLE
document_link() takes a passed resource, but calls resource_link() which uses the current resource

### ISSUE THREAD

**Issue by mkandalf** [nicolaiarocci/eve#549]
The offending line is here in `document_link(resource, ..)`:

`'href': '%s/%s%s' % (resource_link(), document_id, version_part)}`

This creates a link that is based on the current resource, instead of whichever resource is passed in to `document_link`.

Currently, all uses of `document_link` are called with the resource that is in the current request, so nothing is breaking. Nonetheless this seems incorrect.

**Comment by nicolaiarocci** [comment]
thanks I'll have to look into it

**Comment by nicolaiarocci** [comment]
In the past `resource_link`  used to build links based on the `url` setting for the resource. Now we're using `request.path`. `document_link` on the other hand still needs `resource` as an argument, as it needs to grab some settings from the resource configuration.

**Comment by mkandalf** [comment]
So imagine the current request resource is for an `invoice`, but we want to build a link for a related `person` to embed in `_links` (I'm basing this off of the sqlalchemy example). Then calling `document_link` should produce a link with a `href` attribute that is a `url` for a `person`. But as it stands it will produce the incorrect url, `invoice/<person_id>`, rather than `person/<person_id>`, even though we passed `person` as the resource to `document_link`.
