### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by adamczykm** [nicolaiarocci/eve#550]
Is it possible to run Eve over https? This topic isn't mentioned anywhere.

**Comment by touilleMan** [comment]
HTTPs is not handled by Eve, but by the server running it (or the reverse proxy if any)
For example, gunicorn has HTTPs (i.e. SSL) support since version 17 (http://docs.gunicorn.org/en/0.17.0/news.html)

So basically yes, you can run Eve over HTTPs, I'm doing it right now as a matter of fact ;-)

**Comment by adamczykm** [comment]
I must have been tired.. It didn't come into my mind back then. I've realized I can use nginx as a reverse proxy just few moments ago. Thanks for the answer, though!
