### ISSUE TITLE
Document MONGO_URI config option

### ISSUE THREAD

**Issue by mcreenan** [nicolaiarocci/eve#551]
I was trying to determine if Eve supported a list of seed servers for Mongo, and couldn't find anything directly in the docs.

After digging, I found that Eve uses flask-pymongo, which in addition to MONGO_HOST, supports MONGO_URI.  I tried that and it appears to work with Eve as well.

I think it makes sense to document this directly in Eve.

**Comment by nicolaiarocci** [comment]
Absolutely!

**Comment by nicolaiarocci** [comment]
Thanks for brining this up. Docs should be updated now.
