### ISSUE TITLE
Get support to ignore some fields to compute the ETag value

### ISSUE THREAD

**Issue by pfreixes** [nicolaiarocci/eve#555]
Current Eve implementation uses all fields to compute the ETag value, this kind of work is not the best way when some fields can be override by the last update without considering the issues because of the concurrence. There is a draft implementation here [1] that tries to figure it out.

It uses a new field configuration coined `etag_ignore_field` for each resource that says which fields can be left aside to calculate the ETag value for one document. As you can see the field got a list of fields belonging to the resource schema, where nested fields are identified using dictionaries.

```
etag_ignore_fields = ["key1", {"dict": ["key2"]}]
```

Next document shows a raw document with all fields required by the schema gave by one request, with `etag_ignore_fields` set as we saw above ETag value should be compute getting only the `{'dict': {'key3':'value'}}` fields

```
{
    'key1': 'value',
    'dict' : {
        'key2': 'value2',
        'key3: 'value3'
    }
}
```
There is some stuff to do but these are the basics. Let me know if it looks fine then I'm going to finish the work and make the properly pull request.

[1] https://github.com/pfreixes/eve/commit/fda5e704e4fed11b4f7672b794648c883c1433d1

**Comment by nicolaiarocci** [comment]
See my comment on your commit. Other than that, it looks good.

**Comment by nicolaiarocci** [comment]
WIP at #556
