### ISSUE TITLE
Embedded fields in datasource

### ISSUE THREAD

**Issue by StephenHesperus** [nicolaiarocci/eve#560]
When I use ``datasource`` on a resource, the ``embedded_fields`` in the resource is not included in the new api endpoint. Is there any way to embedded those fields in the new endpoint?

Example:
```python
posts = {
    'schema': {
        'category': {
            'type': 'objectid',
            'data_relation': {
                'resource': 'categories',
                'field': 'category',
                'embeddable': True,
            },
        },
    },
    'embedded_fields': ['category'],
}

post_cards = {
    'datasource': {
        'source': 'posts',
    },
}
```
Now, suppose I want to embed ``category`` into ``post_cards``, how can I do so?

**Comment by nicolaiarocci** [comment]
Hello, `source` actually refers `datasource` collection, not the API endpoint (see [Predefined Database Filters](http://python-eve.org/config.html#advanced-datasource-patterns)). So I'm afraid that what you want to achieve can't actually be done (unless you do that via a callback function of course.)
