### ISSUE TITLE
Is there a way to disable the schema validation typo detection in 0.5.2?

### ISSUE THREAD

**Issue by bryder** [nicolaiarocci/eve#565]
I've been (perhaps unwisely)  using the fact that earlier versions of eve have not checked this. 

I have a 'help' field which I use to describe the field because at some point I intend to use eve-docs to describe the fields - rather than just have field names and the validation rules.

EG:

```
'manufacturer_name': {'type': 'string', 'help': 'This should be the value in facter for product_name'}
```

Now that 0.5.2 has been changed to treat these as an error I can't do that anymore.

Is there a standard way  I can tell Cerberus to treat the 'help' field as legal without changing the code?

Or a way to disable this check in Eve?

Or maybe even a better way to do this?

**Comment by touilleMan** [comment]
Cerberus allows you to do that pretty easily : you just need to add a `_validation_help` method to your validation object, for exemple by creating a child Validator class:

```python
from eve.io.mongo.validation import Validator as EveValidator

class Validator(EveValidator):
    def _validate_help(self, help, field, value):
        pass
```

**Comment by nicolaiarocci** [comment]
Or you could [allow the unknown](http://python-eve.org/validation.html#unknown).

**Comment by bryder** [comment]
Thanks for the quick replies!

@nicolaiarocci - I still want my schema checked so I don't want to allow the unknown.

@touilleMan 

I couldn't make it work using your method - but it was really close and put me on the right track.

I did this
```python
from eve.io.mongo.validation import Validator as EveValidator

def _validate_help(self, help, field, value):
    pass

EveValidator._validate_help = _validate_help
```

**Comment by nicolaiarocci** [comment]
@bryder I'm glad that you found a solution. Just to clarify, `allow_unknown` will still validate your schema. It will just quietly pass on unknown fields.

**Comment by bryder** [comment]
Thanks @nicolaiarocci - that's good to know.  Thanks for eve too by the way!

In my case I don't want to allow unknown fields either.

I was pleased to find that eve-docs passed my 'help' field through to the generated documentation too without me having to do anything.
