### ISSUE TITLE
Boolean validation fails in JSON input

### ISSUE THREAD

**Issue by Expi1** [nicolaiarocci/eve#567]
When inputting information from a POST or other method, the validation does not accept boolean values.

    {
        "name":"Example",
        "url":"http://example.com",
        "hidden":"True"
    }

This fails regardless of `hidden` being `"True"`, `True`, `"true"` or `true` and returns a `422 Unprocessable Entity` code.

    'schema': {
        'name': {
            'type': 'string',
            'minlength': 1,
            'maxlength': 30,
            'required': True
        },
        'url': {
            'type': 'string',
            'required': True,
            'regex': urlRegex
        },
        'logo': {
            'type': 'media',
            'required': False,
            'nullable': True
        },
        'hidden': {
            'type': 'boolean',
            'required': False,
            'default': False
        }
    }

**Comment by mcreenan** [comment]
Why are you passing a string for a boolean type? It should be `"hidden": true`

**Comment by Expi1** [comment]
I tried that earlier and could have sworn it didn't work, but now it is, my mistake. Thanks.
