### ISSUE TITLE
Incorrect validation in Eve 0.5.2

### ISSUE THREAD

**Issue by mcreenan** [nicolaiarocci/eve#568]
I upgraded our application using Eve to use 0.5.2.  Our integration tests immediately cause some changes to validation that were unexpected.

See https://gist.github.com/mcreenan/ce366cbb3c5fea17007e

**Comment by nicolaiarocci** [comment]
Hello, I'm on it. From which version did you upgrade?

**Comment by mcreenan** [comment]
Upgraded from v0.4

**Comment by nicolaiarocci** [comment]
Should be fixed now. On "123" being being accepted as an int value, it's been like that since 0.5 since we now simply cast the value to int, and report back if an exception is raised. Not super stellar I agree. Will see if I can come up with a more strict check later on.
