### ISSUE TITLE
Read existing data via eve-mongoengine failed.

### ISSUE THREAD

**Issue by rudaoshi** [nicolaiarocci/eve#569]
I have a mount of data written via mongoengine. But when I set up a eve server and want to read the data, I got the following error about Etags:

    File "/usr/local/lib/python2.7/dist-packages/eve/methods/get.py", line 99, in get

    cursor = app.data.find(resource, req, lookup)

    File "/usr/local/lib/python2.7/dist-packages/eve_mongoengine/datalayer.py", line 390, in find

    qry = self._projection(resource, projection, qry)

    File "/usr/local/lib/python2.7/dist-packages/eve_mongoengine/datalayer.py", line 312, in _projection

    projection = [rev_map[field] for field in projection]

    KeyError: '_etag'

Is it caused by absense of "_etag" fileld in the data written in mongoengine?

If so, Is there any convinent way to save a mount of data convinently with eve? It is somehow diffacult to manage the relationship between objects by hand. 

I use eve with version 0.52. Seems version 0.4 has no such problem.

**Comment by touilleMan** [comment]
Hi,
Eve store the document with along with three additional metadata: `_etag`, `_created` and `_updated`
Thus, you need to have those three fields in all your documents, two way to do that:
1 - write a script to add the fields
 - `_etag` is a sha1 of all fields of the document except _etag if it already exists (see https://github.com/nicolaiarocci/eve/blob/develop/eve/utils.py#L268)
 - `_created` and `_updated` are rfc1123 dates 
2 - use `post_internal` function (see: https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/post.py#L43) to insert all the documents from your original collection into a new one

```python
from eve import Eve
from eve.methods.post import post_internal
from pymongo import MongoClient

app = Eve()
db = MongoClient(host='mongodb://<mongo_host>')[<my_db>]
with app.test_request_context() as c:
    for doc in db.<my_orginal_collection>.find():
        result = post_internal(resource, payload)
        assert result[-1] == 201, result
```

**Comment by nicolaiarocci** [comment]
Starting from 0.5 etags are stored with the document. There's code in place however that makes sure that legacy documents missing the etag don't break the API (etag is computed on the fly). I suspect eve-mongoengine has not been updated to match v0.5 (the traceback shows the exception being raised in eve-mongoengine). Maybe open a ticket over there and see what happens.

**Comment by rudaoshi** [comment]
Thank you both.

@touilleMan , I tried your code, but I got following error:

    assert result[-1] == 201, result
AssertionError: ({'_status': 'ERR', '_issues': {u'_updated': 'unknown field', u'_created': 'unknown field', u'_id': 'unknown field'}, '_error': {'message': 'Insertion failure: 1 document(s) contain(s) error(s)', 'code': 422}}, None, None, 422)

I also tried directly post mongoengine document via: 

    result = post_internal("type", node.to_mongo().to_dict())

It works fine for object without referenceField. However, If one have a reference field, above code broken. Even if I replace the reference object as its objectId, the code also borkenwith error about "_etag"  something.

Have you had any experience about thsi problem?  @nicolaiarocci, will you please also look at this problem, since it is a problem about post_internal in eve. 

Thank you very much.

**Comment by touilleMan** [comment]
> AssertionError: ({'_status': 'ERR', '_issues': {u'_updated': 'unknown field', u'_created': 'unknown field', u'_id': 'unknown field'}, '_error': {'message': 'Insertion failure: 1 document(s) contain(s) error(s)', 'code': 422}}, None, None, 422)

I think your trouble is the payload you try to give to `post_internal` contains some metadata (`_updated`, `_created` and `_id`). Given those metadata are not part of your resource datamodel, the insert failed.

I've updated my previous message, now the snippet should get rid of the metadata before inserting the documents.
