### ISSUE TITLE
how to change eve's host, port, SQLALCHEMY options

### ISSUE THREAD

**Issue by gzliudan** [nicolaiarocci/eve#570]
eve runs at 127.0.0.1:5000, how to change this default host and port in configuration file? I find no options in document(http://python-eve.org/config.html#configuration-with-files).And how to change SQLALCHEMY configuration, use var like SQLALCHEMY_COMMIT_ON_TEARDOWN, SQLALCHEMY_DATABASE_URI and so on?

**Comment by touilleMan** [comment]
By default, eve will try to look for a `settings.py` file located in the same directory than your application's entry point. You can change this by providing a `settings` param when creating the eve app (see https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L112)

Thus, you can store all your configuration in the settings.py file, see the default config file for more informations : https://github.com/nicolaiarocci/eve/blob/develop/eve/default_settings.py

**Comment by gzliudan** [comment]
thanks for your kindly and quick support. 

From your source, I known: pass host, port, debug parameters when execute app.run(). 

My another question is how to save new configuration to setting.py, if I modify some parameters in memory after read configuration from file  settings.py.

**Comment by touilleMan** [comment]
I'm not sure about your question...

If you want to load settings.py, then update it config before initializing Eve, you can use Flask Config:
```
from os import environ
from os.path import dirname, abspath
from eve import Eve
from flask import Config


# Create a Flask Config object
config = Config(dirname(abspath(__file__)))
# Load your settings.py config file
config.from_pyfile('settings.py')
# Customize the config
config['DYNAMIC_CONF_OPT'] = environ.get('DYNAMIC_CONF_OPT', 'default_value')

# Specify settings in Eve, can be:
# - file path (i.g. "settings.py")
# - module path (i.g. "conf.settings"
# - Flask Config object
app = Eve(settings=config)
```

If you want to *save* your updated configuration to settings.py (so actually rewrite the settings.py file on the disk)
 1 - I don't think it's a good idea, configuration is... configuration ! You should not change it during runtime
2 - If you want to do it anyway, I think you will have to read the app.config dict and manualy write a settings.py conf file
```
with open('settings.py', 'w') as fd:
    for key, value in app.items():
        # You should use json.dumps to be able to save dict too
        fd.write('{}="{}"'.format(key, value))
```

**Comment by nicolaiarocci** [comment]
You can also update your application configuration on the fly, like in

    from flask import current_app as app

    app.config['HELLO'] = True

Keep in mind that not everything will be picked up dynamically by Eve though. For example, URL routes are built at startup, so changing them after initialisation won't dynamically update API endpoints (but you can add more by using [`register_resource`](https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L719), see [usage example](https://github.com/nicolaiarocci/eve/blob/develop/eve/tests/io/multi_mongo.py#L21-L30)).

Please keep in mind that GitHub Issues are for reporting bugs and feature requests. For how-tos and general questions see the "Useful Links" section on every page of python-eve.org (on StackOverflow just make sure to flag your question with the 'eve' tag)
