### ISSUE TITLE
Public/Private response for same endpoint

### ISSUE THREAD

**Issue by pratz** [nicolaiarocci/eve#571]
How can I have different response for same endpoint based on authenticated/non-authenticated user, I mean public/private for same endpoint.

Authenticated user (private):
http://127.0.0.1:5000/people -> "all people including secret agents"

Non-Authenticated user (public):
http://127.0.0.1:5000/people -> "all people excluding secret agents"

**Comment by nicolaiarocci** [comment]
Either your endpoint's GET method is public or it is protected. However, you can set up two different endpoints, one public the other private, each querying the same data collection, but with [different queries](http://python-eve.org/config.html#multiple-api-endpoints-one-datasource).
