### ISSUE TITLE
EVE can't find DOMAIN dictionary from UTF-8 format configuration file under windows

### ISSUE THREAD

**Issue by gzliudan** [nicolaiarocci/eve#572]
When I run EVE under windows with configuration file, I find EVE can't find DOMAIN dictionary if the file format is UTF-8 format(below is the error message). But If I save configuration file to ANSI format  with notepad, then EVE can find DOMAIN dictionary . 

D:\Yun\WangKong\Python\gncv5web\api\eve\Scripts\python.exe D:/Yun/WangKong/Python/gncv5web/api/v1/v1.py
Traceback (most recent call last):
  File "D:\Yun\WangKong\Python\gncv5web\api\eve\lib\site-packages\eve\flaskapp.py", line 230, in validate_domain_struct
    domain = self.config['DOMAIN']
KeyError: 'DOMAIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Yun/WangKong/Python/gncv5web/api/v1/v1.py", line 8, in <module>
    app = Eve(data=SQL, settings='app_config.py')
  File "D:\Yun\WangKong\Python\gncv5web\api\eve\lib\site-packages\eve\flaskapp.py", line 127, in __init__
    self.validate_domain_struct()
  File "D:\Yun\WangKong\Python\gncv5web\api\eve\lib\site-packages\eve\flaskapp.py", line 232, in validate_domain_struct
    raise ConfigException('DOMAIN dictionary missing or wrong.')
eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.

Process finished with exit code 1

**Comment by touilleMan** [comment]
I guess you're using python2, if so the default encoding of your file is  ASCII, to change that you must specify the encoding at the beginning of your file:

```python
# -*- coding: utf8 -*-
...
```

**Comment by gzliudan** [comment]
I'm using python 3.4.3 under windows 7 64bit. The first line in source file is already what your suggest. Below is my development environment:
Cerberus (0.8)
cx-Oracle (5.1.3)
Eve (0.5.2)
Eve-docs (0.1.4)
Eve-SQLAlchemy (0.2.1)
Events (0.2.1)
fdb (1.4.4)
Flask (0.10.1)
Flask-Bootstrap (3.3.0.1)
Flask-PyMongo (0.3.0)
Flask-SQLAlchemy (2.0)
itsdangerous (0.24)
Jinja2 (2.7.3)
MarkupSafe (0.23)
pip (6.0.8)
pymongo (2.8)
pymssql (2.1.1)
setuptools (12.0.5)
simplejson (3.6.5)
SQLAlchemy (0.9.8)
Werkzeug (0.10.1)

**Comment by touilleMan** [comment]
I cannot reproduce your trouble on linux (ubuntu 14.04)

test.py
```python
from eve import Eve

app = Eve()
app.run()
```

settings.py
```
# Python3 default encoding is UTF8, you don't have to specify it explicitely

DOMAIN={
    '朋友': {
        'schema': {
            '姓名': {'type': 'string'},
            '地址': {'type': 'string'}
        }
    }
}
```

Then using postman I can access my api:
GET http://localhost:5000/朋友
```
{
    "_links": {
        "self": {
            "title": "朋友",
            "href": "朋友"
        },
        "parent": {
            "title": "home",
            "href": "/"
        }
    },
    "_meta": {
        "page": 1,
        "max_results": 25,
        "total": 0
    },
    "_items": []
}
```

What is interesting in the stack trace you privided in your first post is that you get the same error than if you didn't provide any settings.py file (hence eve couldn't find the DOMAIN dict)
Are you sure your `app_config.py` fil is in the same directory as your main file `D:/Yun/WangKong/Python/gncv5web/api/v1/v1.py` ?

**Comment by gzliudan** [comment]
on windows, if notepad save text file as utf-8 format, it first write 3 bytes on the file head: EF BB BF, then save real data. please test this on windows.

**Comment by touilleMan** [comment]
Damn you stupid BOM, you've made another victim !!! ;-)

As you noticed, Window add a header (the BOM) to UTF8 files
You should then switch you encoding declaration to ` # -*- coding: utf-8-sig -*-`
