### ISSUE TITLE
Integrate with swagger?

### ISSUE THREAD

**Issue by Jonovono** [nicolaiarocci/eve#574]
Hi. I am surprised I have not found anyone asking this yet. 

Is there a way to get EVE working with the swagger library, or swagger-ui? (https://github.com/swagger-api/swagger-ui) It would be cool to have it work together so you could see a browsable api.

**Comment by rs** [comment]
+1

**Comment by nicolaiarocci** [comment]
Hello, it looks like a cool project of which, honestly, I didn't know until today :smile: 

We have something similar with the [Eve-Docs](https://github.com/charlesflynn/eve-docs) extension, although at first glance I'd say that swagger has a much broader scope/feature set.

**Comment by MoOx** [comment]
I would love to be able to use swagger-ui with eve :heart:

**Comment by harobed** [comment]
> I would love to be able to use swagger-ui with eve :heart:

+1

**Comment by bcorso** [comment]
+1. One immediately useful feature swagger has over eve-docs is the ability to test the api request/response right from the doc (live demo: http://petstore.swagger.io/#/ )

**Comment by dtheodor** [comment]
:+1:

**Comment by toxsick** [comment]
I would love this :+1:

**Comment by andy37380** [comment]
swagger-codegen is also cool :+1: 

[swagger-codegen](https://github.com/swagger-api/swagger-codegen)
> swagger-codegen contains a template-driven engine to generate client code in different languages by parsing your Swagger Resource Declaration

**Comment by yxlwfds** [comment]
+1

**Comment by nicolaiarocci** [comment]
I started some experimental work on a eve-swagger extension. See https://github.com/nicolaiarocci/eve-swagger.

**Comment by nicolaiarocci** [comment]
Still a WIP, but usable already. Minimal output is validated by Swagger tooling:

![API docs in Swagger Editor](https://raw.githubusercontent.com/nicolaiarocci/eve-swagger/master/resources/swagger_editor.png)

Cheers

**Comment by cbocta** [comment]
any news from that feature? :-)

**Comment by nicolaiarocci** [comment]
@cbocta [eve-swagger](https://github.com/nicolaiarocci/eve-swagger) is in a "usable" state already. Wish I had the time to work some more on it, but the community can help there too :)
