### ISSUE TITLE
Cerberus 0.8.1 breaks Eve 0.5.2

### ISSUE THREAD

**Issue by rs** [nicolaiarocci/eve#575]
A change in cerberus 0.8.1 adding the `allow_unknown` parameter breaks Eve 0.5.2 release which requires cerberus >0.8,<0.9 and doesn't reflect this API change in its `io.mongo.Validator` sub class.

**Comment by nicolaiarocci** [comment]
I knew that unpinning requirements was going to backfire on my sorry ass :/ https://github.com/nicolaiarocci/eve/issues/378

**Comment by nicolaiarocci** [comment]
Eve 0.5.3 has been released with Cerberus 0.8.1 support. http://nicolaiarocci.com/new-releases-for-cerberus-and-eve/

**Comment by joshvillbrandt** [comment]
We ran into this too. We're specifically stating `Cerberus==0.8` in our app since `Eve==0.5.3` is throwing some other 500's that we'll look into later. Also, 500 errors still aren't CORS compatible it seems.

**Comment by joshvillbrandt** [comment]
By the way, @nicolaiarocci, you should take these two projects out of the `0.` versions so you can start taking advantage of Semantic Versioning. In other words, if Cerberus 0.8.1 had a breaking change, we would have known about it with a new MAJOR version number. Eve would then depend on Cerberus in a fashion that would not allow the MAJOR version number to change.

http://semver.org/
