### ISSUE TITLE
API to support third party components or apps for Eve projects

### ISSUE THREAD

**Issue by pfreixes** [nicolaiarocci/eve#576]
This idea is give a set of functionalities as interfaces to give support for install and exsecute compatible components or apps for Eve projects such as django apps [1] 

I came across with this idea when I was thinking in implement a new user and group app for a Eve project to implement some kind of authorization and authentication system. Obviously a feature like that could be used by other Eve projects. First of all I thought that the way to delivery it could be together with core of Eve project, later I thought that not only this application or component could be implemented to be used further for other Eve projects. 

Because of that I think IMHO that this kind of applications or components should be implemented using a well defined API by Eve. This API should be focused in give a good interfaces for:

* Configuration mechanism to load external but compatible applications or components
* Interfaces to hook the HTTP methods by the applications or components
* One way to publish ad-hoc resources published by the applications or components
* Extend current project resources with other attributes given by the applications or components
* etc

As you can see these kind of characteristics are already implemented by Eve or almost mostly.

Which are your impressions about that ?

[1] https://docs.djangoproject.com/en/1.7/ref/applications/

**Comment by nicolaiarocci** [comment]
Discussion continues on the [mailing list](https://groups.google.com/forum/?hl=en#!topic/python-eve/Zx1iajyEgNY)
