### ISSUE TITLE
find_and_modify with upsert is it possible?

### ISSUE THREAD

**Issue by istinspring** [nicolaiarocci/eve#579]
Hello, 

There is common use case of "update or insert". For instance:

```
        obj = db['data'].find_and_modify(
            {
                'Name': data['Name'],
                'SourcePage': data['SourcePage'],
            },
            data,
            upsert=True
        )
```

Of course can split this request into "GET" and then "PATCH"/"PUT" or "POST" but maybe there is better way?

**Comment by nicolaiarocci** [comment]
Unfortunately there's no way to bind a `find_and_modify` action to standard HTTP verbs. I guess one could achieve the goal with some hack/trick, like a POST with a custom `X_` header, but I don't think we should go down that path really. Also, PUT/PATCH are performed on known ids.
