### ISSUE TITLE
retrieving sub resources returns empty

### ISSUE THREAD

**Issue by guonsoft** [nicolaiarocci/eve#580]
With a sub resource configured as below:

invoices = {
    'url': 'people/&lt;regex("[a-f0-9]{24}"):contact_id>/invoices'

POST to people/&lt;contact_id>/invoices was successful.  The document was created in Mongo collection "invoices".  However, GET people/&lt;contact_id>/invoices returns empty.

    ...

**Comment by nicolaiarocci** [comment]
Hello, did the inserted document include the right contact_id value?

**Comment by guonsoft** [comment]
Actually contact_id was not in the inserted document.  Now I just manually edited the doc to have contact_id added, and it works.  Looks like the missing contact_id is the reason :)

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by guonsoft** [comment]
Hi ... I guess that I didn't say it clearly when I said "manually edited the doc".  I meant that I edited the inserted document in Mongo directly only to test whether the feature will work if contact_id is in the inserted doc.  Eve code change is still needed in order to fix this issue.

**Comment by guonsoft** [comment]
Oh I see.  schema must have contact_id specified as a field as well.  all set.  thanks :)
