### ISSUE TITLE
Upper limit of GET and POST

### ISSUE THREAD

**Issue by sibeliuscn** [nicolaiarocci/eve#581]
Hi,
I define a PAGINATION_DEFAULT=350 and PAGINATION_LIMIT=350,It's works!

But,if I increase the two value ,say 1000,even 500,I got below message from log. 
######################
  File "/usr/lib64/python2.6/socket.py", line 303, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
error: [Errno 32] Broken pipe
######################

Seems it out of the buffer...
So,what is the hard-limit in it?  I expected to run a big data API on eve,hope it can work!

Appreciated :) 

from sibeliuscn@gmail.com

**Comment by nicolaiarocci** [comment]
Hmm this usually means that you are writing to a connection that has been closed by the other end (client). As you can see the error is in the socket not in eve or flask.

[This google search](https://www.google.it/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=error%3a%20%5berrno%2032%5d%20broken%20pipe%20socket) returns a lot of results, see if any of them can help (maybe it is the client closing connection ahead of time?)
