### ISSUE TITLE
HTTPException.response object ignored by the error_endpoint handler

### ISSUE THREAD

**Issue by arnauorriols** [nicolaiarocci/eve#586]
In a project we are currently using the event hooks to do some complex payload validation. In an effort to maintain the consistency of the responses throughout the API, we mimic the validation error responses that are built in the different method functions. To do so, we use the flask.abort() utility:

```python
# Raises UnprocessableEntity(response=make_response(json_response))
flask.abort(422, response=make_response(json_response))
```

This can't work because the HTTPExceptions with code 422 are registered to be handled with the error_endpoint, which ignores the response with which we are creating the HTTPException in the flask.abort() call. An alternative we have is to customize the description of the HTTPException:

```python
# Raises UnprocessableEntity(description=validation_error_msg)
flask.abort(422, description=validation_error_msg)
```

However, the generic payload of response returned by the error_endpoint can't be customized and thus this is not an optimal solution either. 

The only alternative we have is to abort with the base HTTPException class instead of the specialized 'UnprocessableEntity' exception:

```python
# Without code, raises HTTPException(response=make_response(json_response))
flask.abort(make_response(json_response))
```

This 'works', and is what we'll use for the time being, but it is a compromise, not an optimal solution either.
Would it make sense not to ignore the response attribute of an HTTPException in the error_endpoint? At the end, the response attribute of an HTTPException is there to give the user full control over the exact response object that should be returned, thus from my point of view the contract of the HTTPException (and for extension the abort utility) is currently being broken by the error_endpoint handler.

Thanks.

**Comment by nicolaiarocci** [comment]
I'm guessing that an alternative approach would be to replace the handler for `422` with your own implementation. I have not tried it myself but it should be doable, something like `app.error_handler_spec[None][422] = my_handler`. If you do this in your launch script,  you're essentially taking control on 422 errors, bypassing Eve handler. For reference see http://flask.pocoo.org/docs/0.10/api/#flask.Flask.error_handler_spec. Would something like that work for you?

**Comment by arnauorriols** [comment]
Yes, it does work for me, thanks for pointing it out. 

Out of curiosity, though, what is the reason behind overriding the response attribute altogether? I understand wanting to provide a generic response that matches the rest of the API when the HTTPException is raised without response attribute, but I still feel that ignoring the response object when this is explicitly set by the user is kind of harsh. I would assume that, if the user gave an explicit response object, Eve should no longer be responsible for maintaining the consistency with the rest of the API.

**Comment by nicolaiarocci** [comment]
Yes you are probably right. Care to submit a PR for this? I promise I'll review it with due diligence :smile:

**Comment by nicolaiarocci** [comment]
See 8264ccc
