### ISSUE TITLE
On PATCH, subdocuments are always merged

### ISSUE THREAD

**Issue by amagdas** [nicolaiarocci/eve#588]
Currently there is no way to remove a key from a subdocument after it has been added, not even using the dot notation.
Added a failing test for this: https://github.com/nicolaiarocci/eve/pull/587
This got introduced with this commit: https://github.com/nicolaiarocci/eve/commit/026ce09c4ee1f595edc401f94778d39c5bce3742
I  don't think this is the expected behavior for PATCH requests...

**Comment by amagdas** [comment]
@nicolaiarocci Maybe we should revert https://github.com/nicolaiarocci/eve/commit/026ce09c4ee1f595edc401f94778d39c5bce3742?

**Comment by amagdas** [comment]
Actually, I think the proper solution is to keep only readonly fields from the subdocument when resolving the payload to be used by PATCH, I will update my PR with this fix.

**Comment by amagdas** [comment]
Provided a fix for this in #587 , please let me know if it's ok.

**Comment by nicolaiarocci** [comment]
hmm on second thought, how do you exactly remove a field form the main document with PATCH, I don't think it is possible... so why should we change the behaviour for subdocuments? https://github.com/nicolaiarocci/eve/commit/026ce09c4ee1f595edc401f94778d39c5bce3742 was introduced exactly because subdocs were being replaced, while the desired behaviour was to be able to replace subdocuments fields instead.

**Comment by amagdas** [comment]
https://github.com/nicolaiarocci/eve/commit/026ce09c4ee1f595edc401f94778d39c5bce3742 was added so read-only fields in subdocuments won't get replaced, at least that's what I understood from the discussion.
I don't think that's a good behavior to not be able to remove fields from the subdocuments if the field is not read-only, it's quite useful to do so, especially for storing data having a tabular like format.

**Comment by nicolaiarocci** [comment]
That commit also made sure that nested document fields were not being overwritten if not explictly mentioned, as you can see in this test: https://github.com/nicolaiarocci/eve/blob/develop/eve/tests/methods/patch.py#L403. 

While your proposed change does not overwrite readonly fields, it still allows for other fields to be deleted if not explicitly included with the payload, as we can see in your new test (https://github.com/amagdas/eve/blob/replace-subdoc/eve/tests/methods/patch.py#L214). Of course you also had to amend the previously mentioned test, setting the `int`  field to readonly to prevent deletion.

I understand from where you are coming (tabular data), but how about using PUT for these scenarios? I also wonder what @pfreixes would think about this change.

**Comment by amagdas** [comment]
Yup, that's what I was trying to fix/add, be able to remove fields using patch requests.
This is really useful when you have big documents and doing PUT requests each time is not really efficient.

**Comment by nicolaiarocci** [comment]
Maybe we should make it configurable. Something like `OVERWRITE_SUBDOCUMENTS_ON_PATCH`? If True, then subdocuments in PATCH operations are replaced (treated as single field value basically); if False, individual subdocuments fields are updated with the ones contained in the payload. Thoughts?

**Comment by amagdas** [comment]
:+1:  It sounds reasonable, will update the PR with this over the weekend.

**Comment by nicolaiarocci** [comment]
Ok, it is going to be a new feature then so rebase it on top of `develop`.

**Comment by pfreixes** [comment]
Hi, sorry for the delay I was in holidays. @nicolaiarocci thanks to remember about me for this feature, It is truly related with 026ce09.

As you said a kind of configuration variable such as `OVERWRITE_SUBDOCUMENTS_ON_PATCH` will be a good solution with good tradeoff between the new feature claimed by @amagdas and the current implementation.

**Comment by amagdas** [comment]
After thinking on this for a while, I don't think this feature is worthwhile as we would basically replicating a PUT request each time. 
Closing this.
