### ISSUE TITLE
Cache is not invalidated when _latest_version changes

### ISSUE THREAD

**Issue by joshvillbrandt** [nicolaiarocci/eve#597]
@nicolaiarocci,

So I guess I lied when I said there were no impacts to document versioning in #369. Since some fields are synthesized on document retrieval (notably the `_latest_version` attribute), comparing the if-match etag against the etag stored in the document will yield incorrect 304 responses.

Possible fixes:

1. update stored etags for old versions when a new version is saved
1. give up mongo's native projections in favor of performing the projection in the data store abstraction layer
1. make two data store queries for every document - only to get the etag and one to get the projection

Option 1 seems like the path of least resistance. Thoughts?

I still have some investigation to do to prove that this is a problem in the first place, but I wanted to document my progress somewhere because it is dinner time! (I'll either find an existing test or create a new test and will update this ticket with the results.)

**Comment by joshvillbrandt** [comment]
After further review, this does not appear to be an `ETag` problem, but rather an `If-Modified-Since` problem. Moving the [last_modified line](https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/get.py#L222) above the [get_old_document() line](https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/get.py#L215) fixes the problem. This causes the last_modified date of an old version to be the last_modified date of the latest version (just in the headers, not in the actual document) which is I think what we want.

**Comment by nicolaiarocci** [comment]
Are you submitting a fix?

**Comment by joshvillbrandt** [comment]
Yup! Probably on Monday. Also doing #335 next week, though I've been saying that for a while. ;)
