### ISSUE TITLE
24 Character Hexstrings can not be used in where clause

### ISSUE THREAD

**Issue by otibsa** [nicolaiarocci/eve#599]
Values of `string` fields that look like `ObjectID`-values can not be used to look up data:

```python
DOMAIN = {
    'foobar': {
        'type': 'dict',
        'schema': {
            'field1': {'type': 'string'}
        }
    }
}
```
`GET .../foobar`:
```python
... "field1": "0123456789abcdef01234567" ...
... "field1": "55263da3a667813c8730c59a" ...
... "field1": "42" ...
```

But `GET .../foobar?where={"field1": "0123456789abcdef01234567"}` returns no results
Edit:
`GET .../foobar?where={"field1": "42"}` works!

**Comment by nicolaiarocci** [comment]
This should be solvable by setting `query_objectid_as_string` to `True` (see the [configuration docs](http://python-eve.org/config). Let me know if not.

**Comment by otibsa** [comment]
:sweat_smile: 
That did it, thanks!
