### ISSUE TITLE
`unique` schema won't work with a string value looks like a `ObjectId`

### ISSUE THREAD

**Issue by whitetrefoil** [nicolaiarocci/eve#600]
version 0.5.3

I've got a resource which has a field `user` while it's actually a foreign key to the `_id` of `Users` resource.  And I've set that field to be **unique**.

When tried to **POST** `{"user":"552c9d8123cebf1bfcf70c3c"}` multiple times, it just passed every time and created new records in DB every time.

Then I tried to modify that field to a simple `string` and used the same request but it still passed.

I did a quick step tracing and soon found that the query to be used to find the existing record is `{"user":"552c9d8123cebf1bfcf70c3c"}` initially, but it was modified to ``{"user":ObjectId("552c9d8123cebf1bfcf70c3c")}`` after `self._mongotize(v, resource)` at eve/io/mongo/mongo.py line 664.

I guess there may be something wrong which cause a **"`string` looks like `ObjectId`"** to be mistakenly converted to an `ObjectId`.

**Comment by otibsa** [comment]
Correct me if I'm wrong, but this seems to be related to #599.
Have you tried setting `query_objectid_as_string = True`?

**Comment by whitetrefoil** [comment]
Thanks.  I'm taking a look at it.

**Comment by whitetrefoil** [comment]
It fixed the problem actually.  But I don't know if it will have any side effect, since I'm not quite clear what does that purpose to do originally.

I'll take a further look at it.

Thanks a lot.

**Comment by nicolaiarocci** [comment]
Right, I updated the docs. Thanks for pointing that out.
