### ISSUE TITLE
Trying Using Redis

### ISSUE THREAD

**Issue by rizafahmi** [nicolaiarocci/eve#602]
I'm trying using redis instead of mongodb. But it still saved into mongodb. Can you give me some guidance?

This is the github repo: https://github.com/rizafahmi/eve-testdrive

**Comment by nicolaiarocci** [comment]
Hello, currently redis is only used to support the [rate limiting](http://python-eve.org/features#rate-limiting), you can't use it as a datastore for your  endpoints. Available options are mongo (the default), [SQL-Alchemy](https://github.com/RedTurtle/eve-sqlalchemy) or [elasticsearch](https://github.com/petrjasek/eve-elastic).
