### ISSUE TITLE
max_results limited to 50

### ISSUE THREAD

**Issue by fsiddi** [nicolaiarocci/eve#604]
Hello,
I'm trying to do a query with ```max_results==100``` and eve gives me only 50. Basically anything over 50 gets capped back to 50. Is this a known issue?

**Comment by ddurieux** [comment]
See 'PAGINATION_LIMIT' in http://python-eve.org/config.html

**Comment by fsiddi** [comment]
I missed that.
So. Many. Options!
Thanks.
