### ISSUE TITLE
Cannot set auth_field

### ISSUE THREAD

**Issue by hbarroso** [nicolaiarocci/eve#621]
Hello @nicolaiarocci ,

Thank you so much for creating this project. I'm having a blast tinkering with it.
However I'm having an issue regarding the ```auth_field```

I've created a ```users``` collection, and I want my users to be able to update their email, but only their account. However the only author reference I have in that collection is the ```_id``` object, but I can't get it to work. Python returns the following error:

```eve.exceptions.ConfigException: "accounts": auth_field cannot be set to ID_FIELD (_id)```

Here my code:

```
schema = {
    'username': {
        'type': 'string',
        'required': True,
        'maxlength': 50,
        'unique': True,
    },
    'email': {
        'type': 'email',
        'required': True
    },
    'password': {
        'type': 'string',
        'required': True,
    },
   ....
}

domain = {
    'auth_field': '_id',
    'extra_response_fields': ['token'],
    'authentication': auth.Token,
    'resource_methods': ['POST'],
    'item_methods': ['GET', 'DELETE'],
    'schema': schema,
}

```

Am I missing anything ? 
Thanks,

**Comment by nicolaiarocci** [comment]
Could you please post your `auth.Toke` code?

**Comment by hbarroso** [comment]
Sure 

````
from flask import request, current_app as app
from eve.auth import TokenAuth
import jwt


class Token(TokenAuth):
    def check_auth(self, token, allowed_roles, resource, method):
        accounts = app.data.driver.db['accounts']
        #
        # Todo: Add jwt decode
        #
        return accounts.find_one({'token': token})

    def authorized(self, allowed_roles, resource, method):
        token = request.headers.get('authorization')
        return token and self.check_auth(token, allowed_roles, resource, method)
```

But even if I don't include the ```authentication``` domain parameter I'm still getting the same error. I've tried with 0.5.3 and the latest 0.6. Same thing.

**Comment by nicolaiarocci** [comment]
As the error suggests you cannot use set your `ID_FIELD` as the `auth_field`, so this line:

        'auth_field': '_id',

Needs to be replaced with something like `'auth_field': 'my_auth_field'`. Then you also need to actually set the auth_field value in your authentication class. For guidance see http://python-eve.org/authentication.html#user-restricted-resource-access
