### ISSUE TITLE
Python Eve Framework Authentication not getting applied to selected APIs

### ISSUE THREAD

**Issue by tusharsappal** [nicolaiarocci/eve#623]
I am writing APIs in Python Eve ,to implement the authentication I followed the documentation written at <a href="http://python-eve.org/authentication.html#basic">Python Eve Authentication </a>

My authentication Class code is as follows :-

    __author__ = 'sappal'

    from eve.auth import BasicAuth

    class SampleAuth(BasicAuth):
      def check_auth(self, username, password, allowed_roles, resource, method):

        if method == 'GET' and resource == 'org':
          print "Inside GET Method for Org Resource"

        elif method == 'POST' and resource == 'org':
          print "Inside POST Method for Org Resource "

        elif method == 'GET' and resource == 'people':
          print "Inside GET Method for People Resource"

        elif method == 'POST' and resource == 'people':
          return True
        else:
          return username == 'admin' and password == 'secret'

As the code states that I am making POST call on people end-point free of authentication {And that is what I intend to do} ,But When I am making a POST call on the people endpoint [http://127.0.0.1:5000/people] .

I am getting the following Response 

    {"_status": "ERR", "_error"
         {
           "message": "Please provide proper credentials", 
           "code": 401
         }
    }

Please help and guide me ,what I am doing wrong.

**Comment by nicolaiarocci** [comment]
Following up on SO. Please don't cross-post.

**Comment by jwfuller** [comment]
http://stackoverflow.com/questions/30130196/python-eve-framework-authentication-not-getting-applied-to-selected-apis
