### ISSUE TITLE
XML error while rendering tags with spaces.

### ISSUE THREAD

**Issue by istinspring** [nicolaiarocci/eve#627]
This is valid JSON

```json
            "specs": {
                "Brand": "Magic Bullet",
                "Item EAN": "2724286709737",
                "Equipment Type": "Food processors"
            }
```

but invalid XML

```text
This page contains the following errors:

error on line 1 at column 950: Specification mandate value for attribute Type
```

according to this docs http://wiki.libvirt.org/page/Common_XML_errors#Typos_in_tags spaces are not allowed for XML tags, while it's totally OK for mongodb and JSON.

**Comment by nicolaiarocci** [comment]
hmm can you post the XML output from Eve?

**Comment by istinspring** [comment]
Sure.

```xml
<resource href="products/555560164dc782679f570745"  title="Product" >
  <_created>Fri, 15 May 2015 02:55:18 GMT</_created>    
  <_etag>a36bb7f7fe8b3df564263fa5cdd3bb40d8b4a36e</_etag>   
  <_id>555560164dc782679f570745</_id>
  <_updated>Fri, 15 May 2015 03:21:26 GMT</_updated>
  <category>WOW Deals</category>
  <descount>33% OFF</descount>
  <description>Turn ordinary food into superfood with the NutriBullet. It has a powerful 600 watt motor and extractor blade that can open seeds, crack through stems, shred skins, and access hidden nutrients in food. It breaks down food to its most digestible state so you can drastically improve your health and</description>
  <keywords>Magic Bullet</keywords><keywords>Food Preparation</keywords>    
  <prev_price>449.0</prev_price><price>299.0</price>
  <sold>76% Sold</sold>
  <specs>
    <Brand>Magic Bullet</Brand>
    <Equipment Type>Food processors</Equipment Type>
    <Item EAN>2724286709737</Item EAN>
  </specs>
  <title>MB NutriBullet 12 Piece Set</title>
</resource>
```

Eve output for xml seems to be ok, but FF, Chrome and Safari show error message and don't render it as usual. I.e. produced XML is not valid.

**Comment by nicolaiarocci** [comment]
Thanks. Yes looks like we should get rid of spaces but I'm not sure this should be automatically handled for the maintainer. Maybe if you want XML output you should name your fields in a way that they don't break the rules? Otherwise we would end up having two different keys for same field: "Document Type" for JSON and "DocumentType" for XML.

**Comment by istinspring** [comment]
Probably need to add warning about inappropriate field name. I finished with wrapping data into the list of dictionaries like [{'name': 'Title1', 'value': 'Value2'}, ...]
