### ISSUE TITLE
Oplog domain entry is not created if OPLOG_ENDPOINT==False

### ISSUE THREAD

**Issue by amorphic** [nicolaiarocci/eve#628]
The docs imply that it should be possible to enable an *oplog* without exposing it as an endpoint:

> "As you can see the oplog feature is turned off by default. Also, since OPLOG_ENDPOINT defaults to None, even if you switch the feature on no public oplog endpoint will be available. You will have to explictly set the endpoint name in order to expose your oplog to the public."

The docs also state that:

> "Also, unless you need to customize it, adding an oplog entry to the domain is not really necessary as it will be added for you automatically."

However `_init_oplog` will only add the oplog entry to the domain if OPLOG_ENDPOINT is defined:

    if endpoint:
        settings = self.config['DOMAIN'].setdefault(name, {})

        settings.setdefault('url', endpoint)
        settings.setdefault('datasource', {'source': name})

        # this endpoint is always read-only
        settings['resource_methods'] = ['GET']
        settings['item_methods'] = ['GET']

        # schema is also fixed. it is needed because otherwise we
        # would end up exposing the AUTH_FIELD when User-Restricted-
        # Resource-Access is enabled.
        settings['schema'] = {
            'r': {},
            'o': {},
            'i': {},
        }
        ...

So if the oplog is enabled by setting `OPLOG=True` and an endpoint is not set by leaving the default `OPLOG_ENDPOINT=False`, we encounter errors like this:

      File "my_venv/lib/python2.7/site-packages/eve/methods/post.py", line 40, in post
        return post_internal(resource, payl, skip_validation=False)
      File "my_venv/lib/python2.7/site-packages/eve/methods/post.py", line 231, in post_internal
        oplog_push(resource, documents, 'POST')
      File "my_venv/lib/python2.7/site-packages/eve/methods/common.py", line 937, in oplog_push
        resolve_user_restricted_access(entry, config.OPLOG_NAME)
      File "my_venv/lib/python2.7/site-packages/eve/methods/common.py", line 764, in resolve_user_restricted_access
        resource_def = app.config['DOMAIN'][resource]
    KeyError: 'oplog'

**Comment by nicolaiarocci** [comment]
Thanks, should be fixed now.
