### ISSUE TITLE
eve.exceptions.ConfigException: A resource schema must be provided when POST or PATCH methods are allowed for a resource [people].

### ISSUE THREAD

**Issue by suryamuppalla** [nicolaiarocci/eve#630]
DOMAIN = {
    #'items':items,
    'people': {
        'authentication': 'MySuperCoolAuth',
        'source': people,
        'resource_methods': ['GET', 'POST'],
    }
}

**Comment by nicolaiarocci** [comment]
Hello,

the exception message is pretty self explanatory: there is no `schema` definition for your `people` endpoint. That is required since you POST is enabled on the resource. See [Schema Definition](http://python-eve.org/config#schema-definition) in the docs for more details.
