### ISSUE TITLE
Best way to add new endpoints to an Eve app

### ISSUE THREAD

**Issue by andresmrm** [nicolaiarocci/eve#631]
Hi! Probably missed something, but I didn't find an example about this in the docs: what's the best way to add a new endpoint to my app? (this endpoint gets some data from the DB, do some processing and returns the result as JSON)
I tried simply adding a new Flask route, but had to add CORS by my own via Flask-Cors, and this endpoint probably won't show up in Eve autogenerated docs, so it doesn't seem the right way of doing it...

**Comment by amagdas** [comment]
Hi, you can check the demo project here:  https://github.com/nicolaiarocci/eve-demo/blob/master/settings.py
Basically you have to specify the resource configuration and add it to the Eve domain.

**Comment by nicolaiarocci** [comment]
Also, if you want to register a resource after app initialization, you can use `register_resource`. There are several example in recent tests, [here's](https://github.com/nicolaiarocci/eve/blob/c264ab6e9c12ea891eca0458257ac5ad4bdc0eca/eve/tests/config.py#L429-L441) one.

**Comment by andresmrm** [comment]
Thanks for the answers, but my new endpoint (as far as I can see) is not a resource.
The endpoint uses some resources, but needs to do some extra calculations that Eve doesn't do for its common resources. So I need to create a Python function to describe the calculations, and need the new endpoint to call this function.

**Comment by nicolaiarocci** [comment]
Ahh you probably want to register a Blueprint then. I usually point people to the [Eve-Docs](https://github.com/charlesflynn/eve-docs) extension for an usage example. It adds a `/docs` endpoint which is totally out of Eve's own endpoint management (serves static html).

**Comment by andresmrm** [comment]
But that's the point: I want to be "inside" Eve's endpoint management. So, for example, my new endpoint shows up in the docs (like the Eve's endpoints), and if I set CORS everywhere at `settings.py`, my new endpoint has CORS enabled too.

I thought it was a common use case: to add extra managed endpoints to Eve.
Eve is quite good to give a basic API to my resources, but sometimes I need more endpoints, that do some transfomations on the data before returning it. And these are still endpoints of my API, so they need a Doc, they need CORS, they need all the beautifull stuff Eve gives to the other endpoints.

**Comment by amagdas** [comment]
Usually you would use the standard events for this kind of work, like
on_create, on_created, on_fetched.

**Comment by andresmrm** [comment]
Seems to solve some use cases, especially with http://python-eve.org/config.html#multiple-api-endpoints-one-datasource .
What if I want to use multiple resources (sources) in one endpoint?

**Comment by andresmrm** [comment]
Or if it's an endpoint that needs to do 2 DB queries to answer a GET?

**Comment by nicolaiarocci** [comment]
I'm afraid none of these scenarios is supported. You could probably achieve something like that by using event hooks as @amagdas suggested.

**Comment by andresmrm** [comment]
Ok. Thanks! 


Quoting Nicola Iarocci (2015-05-29 10:01:23)
