### ISSUE TITLE
Strings converted to ObjectId?

### ISSUE THREAD

**Issue by g----** [nicolaiarocci/eve#633]
If I have `unknown_field` which is string representation of `ObjectId` and I make a query - Eve returns empty list. If I convert the same field to `ObjectId` Eve acts as expected.

Is there any default behavoir that tries to convert string to `ObjectId` before qurying Mongo (I didn't check yet)?

Wouldn't it be nice to check schema before doing such thing? If field is not in scheme just proceed with querying for string field?

**Comment by nicolaiarocci** [comment]
Try setting `query_objectid_as_string` to `True` and see if it solves your issue. See [docs](http://python-eve.org/config#resource-item-endpoints).

**Comment by g----** [comment]
Works like a charm. Thought it's a bug. I wouldn't expect that such thing is configurable:)

Thanks Nicola!
