### ISSUE TITLE
PUT should be able to create a document with a user defined ID

### ISSUE THREAD

**Issue by rs** [nicolaiarocci/eve#634]
Following the [REST principals](http://en.wikipedia.org/wiki/Representational_state_transfer#Applied_to_web_services), a `PUT` request performed on an element (item in Eve terminology) URI should replace an existing member or create it if it doesn't exist:

> **Replace** the addressed member of the collection, or if it does not exist, **create** it.

Within Eve, if the document doesn't already exist, a 404 is returned with no option to create the document with a user defined `id` complying with the format defined for the id field.

When document doesn't exist, instead of returning a 404 error we could use the data layer's `insert` instead of a `replace` in order to make sure we don't overwrite an existing item owned by someone else.

**Comment by rs** [comment]
BTW, we can get the wanted behavior by performing a `POST` on the resource with the `_id` field set. But this is the role of `PUT` and a `POST` shouldn't allow that IMHO.

**Comment by matthieuprat** [comment]
:+1:

According to [RFC 7231](http://tools.ietf.org/html/rfc7231#section-4.3.4):
> The PUT method requests that the state of the target resource be created or replaced with the state defined by the representation enclosed in the request message payload.

**Comment by matthieuprat** [comment]
> BTW, we can get the wanted behavior by performing a POST on the resource with the _id field set. But this is the role of PUT and a POST shouldn't allow that IMHO.

I'm wondering if we would want to disallow updates via POST though. According to [RFC 7231](http://tools.ietf.org/html/rfc7231#section-4.3.3):

> The POST method requests that the target resource process the representation enclosed in the request according to the resource's own specific semantics.  For example, POST is used for the following functions (among others):
- Providing a block of data, such as the fields entered into an HTML form, to a data-handling process;
- Posting a message to a bulletin board, newsgroup, mailing list, blog, or similar group of articles;
- Creating a new resource that has yet to be identified by the origin server; and
- **Appending data to a resource's existing representation(s).**

And:

> If the result of processing a POST would be equivalent to a representation of an existing resource, an origin server MAY redirect the user agent to that resource by sending a 303 (See Other) response with the existing resource's identifier in the Location field.

**Comment by nicolaiarocci** [comment]
PUT would basically allow [upserts](http://docs.mongodb.org/manual/tutorial/modify-documents/#upsert-option), which is probably a nice thing to have. Such a feature should probably be configurable. We could  introduce a `ITEM_UPSERT` or perhaps more explicitly `UPSERT_ON_PUT`, defaulting to `True`. Thoughts?

**Comment by rs** [comment]
If disabled, you would also disable the possibility to choose doc id via POST? I don’t see why one would allow one and not the other.

**Comment by nicolaiarocci** [comment]
I feel like POST is fine, I'm sure there are people out there performing bulk inserts of elements with known ids, and they would hate to be confined to single-document PUTs instead. Unless we want to make that one behaviour configurable as well, but I'm not a big fan of allowing too much customization when it comes to REST principles: Eve has always been strongly opinionated after all.

**Comment by nicolaiarocci** [comment]
wow I totally misunderstood your question.

**Comment by matthieuprat** [comment]
Thanks!

**Comment by nicolaiarocci** [comment]
Also added support for `UPSERT_ON_PUT`, defaults to `True`.
