### ISSUE TITLE
Handling custom MediaStorage files urls

### ISSUE THREAD

**Issue by hbarroso** [nicolaiarocci/eve#639]
Hey guys,

So, I'm currently implementing an custom MediaStorage to be used with S3. Everything works fines, however I really don't like how Eve handles the returned media file urls. 

When I use ```RETURN_MEDIA_AS_URL``` this always returns the URI related to the API address, but I actually needed to return a full URL like: ```"https://s3-us-west-2.amazonaws.com/foo/<:file_id>"``` but I can't because the ```resolve_media_files()``` method in eve.methods.common does't allow it.

It makes perfect sense for GridFS but custom MediaStorage not so much

```
...
        if _file:
            # otherwise we have a valid file and should send extended response
            # start with the basic file object
            if config.RETURN_MEDIA_AS_BASE64_STRING:
                ret_file = base64.encodestring(_file.read())
            elif config.RETURN_MEDIA_AS_URL:
                ret_file = '%s/%s/%s' % (app.api_prefix,
                                         config.MEDIA_ENDPOINT,
                                         file_id)
            else:
                ret_file = None
...
```

I think that ret_file formatted string should be user customized  if needed. Is there a way around this for the time being ?

Thanks :)

**Comment by hbarroso** [comment]
I just sent a pull_request that allows this here: #640 . Let me know if this would be a good solution. Thanks

**Comment by nicolaiarocci** [comment]
See my comment on the PR thread. Thanks!
