### ISSUE TITLE
No way to reset / delete one or more fields of a document (on PATCH)

### ISSUE THREAD

**Issue by cyppan** [nicolaiarocci/eve#653]
My primary need is to nullify a field in a partial update, or even remove it from a document. It seems to be impossible with the current approach of patching. I could use a PUT specifying the entire document in the payload except the specific field, but I don't really like this approach, PATCH is safer to use with concurrent accesses.
The patch endpoint transforms the sent payload into a mongo update operator {'$set': payload}. This is sufficient for most cases, and could be sufficient for mine too but the Eve validator on the other side don't allow me to specify "field": null in my payload (even if the field is not required).
Am I missing something?

**Comment by nicolaiarocci** [comment]
If you set `nullable: True` for the field, then it should be possible to reset it to null.

**Comment by cyppan** [comment]
Yes it is, thank you.
