### ISSUE TITLE
Thoughts on If-Match header support

### ISSUE THREAD

**Issue by rs** [nicolaiarocci/eve#657]
I don't really understand why the `IF_MATCH` option is so binary. Either you enable it and all your edit calls must be conditional or you have to disable it altogether. That is so annoying, especially when you are developing or testing the API, that I think the first thing most people do (as I did) is to disable this feature.

HTTP never require the If-Match header, even when Etag header is returned and I think it should be the same in Eve by default when `IF_MATCH` is enabled. You may have a `FORCE_IF_MATCH` configuration option if you want to enforce the use of conditional request though.

Also, the `Etag` shouldn't be in the payload but returned as a ETag header. If the client is not able to read that header, he won't be able to set the `If-Match` header anyway.

**Comment by petrjasek** [comment]
agree in general, but imo `etag` in payload is useful in the list, so that you can update item without fetching it first

**Comment by nicolaiarocci** [comment]
> HTTP never require the If-Match header, even when Etag header is returned and I think it should be the same in Eve by default when IF_MATCH is enabled. You may have a FORCE_IF_MATCH configuration option if you want to enforce the use of conditional request though.

Just to make sure that I get it right, your suggestion is that, when `IF-MATCH` is enabled, the client gets to decide wether the request should be conditional or not. If If-Match is included, then it should be considered a conditional request and the API will validate the etag value. If no If-Match is included, then the request is simply processed with no conditional checks. However, if (the new) `FORCE_IF_MATCH` option is active, then all requests are to expted to include the If-Match or they will rejected (like it is now when `IF-MATCH` is on). Am I correct? 

> Also, the Etag shouldn't be in the payload but returned as a ETag header. If the client is not able to read that header, he won't be able to set the If-Match header anyway.

We could always have a `ETAG_IN_PAYLOAD` option.

**Comment by rs** [comment]
That is exactly it.

**Comment by nicolaiarocci** [comment]
Seems reasonable. I would call the new option `ENFORCE_IF_MATCH` and make sure it is active by default in order to not to cause regressions once it's released.

**Comment by rs** [comment]
Ok think it’s an unintuitive default but you decide.

**Comment by artburkart** [comment]
@nicolaiarocci - not sure if it's of any interest, but I took a stab at this one.
