### ISSUE TITLE
Thoughts about X_DOMAINS regex support

### ISSUE THREAD

**Issue by stt** [nicolaiarocci/eve#660]
X_DOMAINS doesn't support sites with dynamic range of subdomains, as e.g. many SaaS setups use them.

Adding this support could potentially be as simple as changing https://github.com/nicolaiarocci/eve/blob/444817/eve/render.py#L214 to
`elif any(re.match(domain, origin) for domain in domains):`
but this has couple of problems..

1) simple "*" should still be supported for backwards compatibility but it's not a valid regex
2) unescaped dots of old X_DOMAINS definitions would interpreted as any character causing security issue with bad guy registering wwwxgithub.com to pass as www.github.com

So, any opinions about  introducing X_DOMAINS_RE as a regex alternative?

**Comment by nicolaiarocci** [comment]
X_DOMAINS_RE looks like a good solution to me.

**Comment by harryjubb** [comment]
Any news on this?

**Comment by nicolaiarocci** [comment]
Hello,

I just pushed a possible fix. It does not add `X_DOMAIN_RE`. Instead if allows (supposedly safe) use of regexes with existing `X_DOMAIN` setting. I would really appreciate if you guys could test this and report back.

**Comment by harryjubb** [comment]
Awesome, thank you, will do!

**Comment by stt** [comment]
Totally forgot about creating this issue (would be nice if github could send a reminder like once a month).
Thanks for picking it up Nicola.
