### ISSUE TITLE
stop or prevent insert on event on_insert_tablename

### ISSUE THREAD

**Issue by PenguinMe** [nicolaiarocci/eve#667]
Hi, I want to know if I could stop or prevent insert on event on_insert_tablename.
I write some code on on_insert_tablename event.
```python
def on_insert_tablename(items):
    delList=[]
    for item in items:
        delList.append(item)
    for i in delList:
        items.remove(i)
```

But I got 500 error. So I want to know is there any way to stop insert on event on_insert_tablename.
Thanks for helping.

**Comment by nicolaiarocci** [comment]
Hello if you turn debug mode on you will see that the error is `pymongo.errors.InvalidOperation: cannot do an empty bulk write`. In short you cannot submit an empty list for insertion. 

You *can* alter the list (try with `items.pop(0)`), but not to the point to make it empty.

**Comment by PenguinMe** [comment]
Thanks, but I just have to clear the list for the data should not be inserted into database. I will try other methods, example,  add table "tablenametemp" to do the temp data and decide whether insert into table "tablename" or not.

**Comment by nicolaiarocci** [comment]
Or you could just abort the request. You're not going to add anything anyway.
