### ISSUE TITLE
Please support rethinkdb

### ISSUE THREAD

**Issue by somenxavier** [nicolaiarocci/eve#668]
Hi,

I think that it would be useful if you supported rethinkdb. It's similar to mongodb, so I think you will not have port problems...

**Comment by nicolaiarocci** [comment]
Feel free to start work on an extension like [Eve-SqlAlchemy](https://github.com/RedTurtle/eve-sqlalchemy/). I will be happy to post about it on the eve website. Rest assured, contributors will join in.

**Comment by somenxavier** [comment]
I have not the skills for doing it. It was a wish... but if you didn't want to do it....

**Comment by ddurieux** [comment]
I'm ok with @nicolaiarocci it will be as an extension

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by feluxe** [comment]
+1 for support
