### ISSUE TITLE
Resources resolution does not work if _id is not of type ObjectId

### ISSUE THREAD

**Issue by afedulov** [nicolaiarocci/eve#673]
If _id is stored as a String, resources lookup does not work.

Description:
http://127.0.0.1:5000/items/item1 works fine if _id is of type ObjectId("item1")
http://127.0.0.1:5000/items/item1 fails with 404, resource not found, if the same item is defined with _id of type String("item1")

**Comment by nicolaiarocci** [comment]
Make sure `item_url` is set to something like `'regex("[\w]+")'` in your resource configuration. By default `item_url` matches a ObjectId.
