### ISSUE TITLE
[0.6-dev] possible regression using 'readonly' when custom url or auth_field

### ISSUE THREAD

**Issue by cyppan** [nicolaiarocci/eve#677]
I've written "possible" because I'm not sure about the correct way to handle this. Is it a bug? a feature? At least literally it's a "regression" for us.
Actually, we used to set 'readonly' on resource fields that was injected automatically by Eve (for custom url with <regex:field> syntax or auth_field). 
Now the framework fails to insert such resources saying that 'field is readonly'.
What do you think?

**Comment by nicolaiarocci** [comment]
If the resource field is injected by Eve, then it should not be in the resource definition in the first place. Can you provide me with an example of what you were doing and why? 

I tried setting a regular field as read-only and then updating it in within a callback function, and it will let me do so (and still not allow a client to update it).
