### ISSUE TITLE
[pymongo3] Eve does not handle BulkWriteError exception

### ISSUE THREAD

**Issue by mcreenan** [nicolaiarocci/eve#680]
It looks like there were some changes to the pymongo 3.x driver that affected what exceptions were throw in certain scenarios.

Example: 
* With 2.x, if I did a bulk insert with a single record, for a collection using a unique index, and that record already exists, it would raise a DuplicateKeyError exception, which Eve is able to handle.
* With 3.x, it simply throws a BulkWriteError exception.  The details property of the exception object contains a key called writeErrors, which contains an array of objects. Within that object is a code with the value 11000, which represents a duplicate key error.

I'm not sure how this should be handled, but I think Eve needs to handle a BulkWriteError then decide what HTTP status code to return and what payload to return.

If you try to insert 2 records and 1 record suceeds while the other throws a duplicate key error, how should Eve handle this?  I don't have a good suggestion :(

**Comment by nicolaiarocci** [comment]
Yeah Eve is not pymongo 3 compatible yet. I have a branch which supports it, and I'll make sure to consider this ticket when I finally go back to it, but everything is on freeze right now as Flask-PyMongo  does not support pymongo3 yet (I'm using a custom fork of Flask-PyMongo on that branch).

**Comment by mcreenan** [comment]
Looks like it's not only actual bulk inserts.

If I do a POST with a single record (no array wrapper), I get:
``pymongo.errors.OperationFailure: batch op errors occurred``

Looking at the code, it looks like it always converts a single record to an array and treats it as a bulk insert.

**Comment by txomon** [comment]
Yeah, I came here because I have found that the exception handling in https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/mongo.py#L417-L435 is no longer valid.

With the new implementation, a except on pymongo.errors.BulkWriteError should be written and parse all the 'writeErrors' array to report them back to the user.

I would fix it myself but I don't know how you can pass more than one error up (if there exist many errors, how you report all of them together)

**Comment by nicolaiarocci** [comment]
Finally got around to address this. Should be "good enough", at least for the time being (see note in the comments).
