### ISSUE TITLE
is argument "updates" meant to be "updated" for on_updated call

### ISSUE THREAD

**Issue by guonsoft** [nicolaiarocci/eve#682]
In patch.py, "updates" is used when calling on_updated callbacks.  Is it meant to be "updated" instead?  "update" has done its work and won't be used anymore in building the response.

            getattr(app, "on_updated")(resource, updates, original)
            getattr(app, "on_updated_%s" % resource)(updates, original)

**Comment by nicolaiarocci** [comment]
Well I guess it's all about semantics: `updates` is meant to mean "updates requested" or "updates performed", which is appropriate I believe?

**Comment by guonsoft** [comment]
Sorry I might not have described it clearly.  I think it is a typo/bug otherwise the on_updated* hooks won't have any effect to the final response.  By the time the code gets to this point, it has both documents "update" and "updated".  "updated" contains the result and is the document feeding into build_response_document() to build full response.

**Comment by nicolaiarocci** [comment]
Oh I see what you mean now. You would rather have the updated document back in your callback function, rather than the updates sent with the request.

**Comment by sphet** [comment]
I know this is closed, and I hate to necro it, but I don't understand how I am supposed to get the complete updated item record in the callback. It seems like this patch update passing back the updated item. What is the correct way to get the updated item - is it to take the original and update it with updates myself in the callaback?
