### ISSUE TITLE
Provide a basic home page response when HATEOAS is off

### ISSUE THREAD

**Issue by stratosgear** [nicolaiarocci/eve#685]
What would you think about returning some basic EVE info in the home page?

An example, from elasticsearch, to illustrate my point:

    {
        status: 200,
        name: "Julie Power",
        cluster_name: "elasticsearch",
        version: {
            number: "1.7.1",
            build_hash: "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
            build_timestamp: "2015-07-29T09:54:16Z",
            build_snapshot: false,
            lucene_version: "4.10.4"
        },
        tagline: "You Know, for Search"
    }

Not all of the fields makes sense for Eve, I know, but I think you get my point.

This can also serve as a nice way to check if Eve is still up an running if you are pinging your server to make sure it is still up and running and responding to requests.

**Comment by nicolaiarocci** [comment]
When HATEOAS is disabled and you hit the homepage:

- You can check the `Server` header to make sure that Eve us up and running (it will contain something like `Eve/0.6 Werkzeug/0.10.4 Python/2.7.8`);
- if debug mode is on, you get a `HATEOAS is disabled so we have no data to display at the API homepage` message.

Now of course you don't use debug mode in production, so I guess you are left with the server header option. Would that be enough for both pinging the API and checking its version? Since HATEOAS has been disabled, I can't think of any other information might be useful there.

**Comment by stratosgear** [comment]
Some more comments...

Hitting the home page (with HATEOAS off) it results in:

    {
      "validation": "ERR",
      "error": {
        "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",
        "code": 404
      }
    }

This is, imho, an "ugly" page.  I can read and understand the error message, but it is not a friendly welcome page as the home page to a new user of the API.  It looks like something is not working right.

On the other hand, a status/version reply (as in the elasticsearch example above) looks more "comforting" that at least everything is working as intended and gives an easy to read info about the server, without having to investigate headers (which are missing the API version, btw).

So all in all, I consider the home page as the first page someone will try to test, and seeing an error page gives a wrong/unprofessional impression, especially when something can be easily implemented and to provide some useful info to the end users.

But that's just **my** take on the matter... :)

**Comment by stratosgear** [comment]
Just created a PR that implements what I mentioned above (with tests too)

It replies with a simple:

    { 'eve_version': 'a.b.c', 'api_version': 'x.y.z'}

Most of my time was spend trying to figure out a Travis error from flake8 about an unused import in endpoints.py, than implementing this "feature".
