### ISSUE TITLE
How to delete specified items,not all items

### ISSUE THREAD

**Issue by andy37380** [nicolaiarocci/eve#687]
I want to delete specified items by _id, like below:

    curl -X DELETE "https://127.0.0.1/books?where={ "_id": { "$in": ["55d457affe80291364edb145","55d457b0fe80291364edb146"] } }

But it will delete all items,how can I do that?

**Comment by nicolaiarocci** [comment]
Not supported. a DELETE on the resource endpoint will clean the resource. You can do single item deletes, one request per item.
