### ISSUE TITLE
data_relation question

### ISSUE THREAD

**Issue by hbarroso** [nicolaiarocci/eve#688]
Hi guys,

I'm having trouble implementing something that I thought would be straightforward at first, but it's revealing to be a headache, or maybe I'm not looking at it in the right perspective.

Here's the thing. Let's assume we have the following domain setting:

```json
{
  "users": {
    "schema": {
      "username": {"type": "string"},
      "password": {"type": "string"},
      "full_name": {"type": "string"},
      "token": {"type": "string"},
    }
  },
  "posts": {
    "schema": {
      "body": {"type": "string"},
      "title": {"type": "string"},
      "author": {"type": "objectid", "data_relation": {"resource": "users"}}
    }
  },
  "comments": {
    "schema": {
      "body": {"type": "string"},
      "post": {"type": "objectid", "data_relation": {"resource": "posts"}},
      "author": {"type": "objectid", "data_relation": {"resource": "users"}}
    }
  }
}
```

I want that each posts or comment to be submitted by the current logged_in user (auth_id value), and that all authenticated user can read it, but can't update it unless they are the creator.

So, I read in the docs that using the ```auth_id``` setting would make all added items to be associated with the authenticated user. But the thing is, everyone else won't be able to read it, as that option will forbidd everyone else to read,update,delete unless they are the original creator. I thought: "well, I'll just add a ```GET``` to the ```PUBLIC_METHODS```" and this works, but it works even for non-authenticated users.
Is there any other way, to make a collection write-only to the user but with reading access just for authenticated users ?

One other thing I thought was,  to drop the ```auth_id``` and just use it with ```data_relation```. 
But wouldn't this allow sneaky users to post/update items using someone else's ```_id``` ? eg: Submitting a comment to a post using another id. Is there any other way to prevent this. I understand a framework is not silver bullet and sometimes we need to extend it to make it work our way, but I thought of asking you first instead of reinventing the wheel.

Thanks,

**Comment by andy37380** [comment]
I think it will work fine
```
"public_posts": {
	"auth_field":None,
	"resource_methods": ["GET"],
	"datasource": {
		"source":"posts"
	}
}
```

**Comment by hbarroso** [comment]
That's a good idea, but I want to keep it under the same domain. Maybe it's something that I have to extend in order to make this work for me.

**Comment by andy37380** [comment]
another way
```
def check_auth(self, token,  allowed_roles, resource, method):
#ignore
	if '_id' in account:
		if method == 'GET' and resource in ['posts','comments']:
			pass
		else:
			self.set_request_auth_value(account['_id'])
#ignore
```

**Comment by hbarroso** [comment]
Oh, that's actually very clever solution ! Thank you so much @andy37380 , this totally works for me. Closing this.
