### ISSUE TITLE
Resource-specific id field

### ISSUE THREAD

**Issue by dkellner** [nicolaiarocci/eve#690]
We'd like to be able to configure id_field per resource. This way, most resources could use 'id' as primary key / id field, and some might use another meaningful column, like 'sku' for products etc. It would be intuitive to write something like:

```python
DOMAIN = {
    'products': {
        'schema': {
            'sku': { 'type': 'string' },
            'title': { 'type': 'string' }
        },
        'id_field': 'sku',
        'item_lookup_field': 'sku',
        'item_url': 'regex("[a-z0-9_]+")'
    }
    # ...
}
```

I was able to implement this in Eve [1] and like to contribute my changes back to the main tree. All existing tests pass, but I might need some guidance regarding the implementation of new tests covering the new functionality. I can think of at least a few special cases we need to check:
- Do relations work properly when referring to a resource with a custom id field?
- Is uniqueness of the custom id field always ensured?
- Do subresources work properly when custom id fields are involved?

My next step would be to introduce a new resource in eve/tests/test_settings.py with a custom id field to be able to test the "standard" cases (like GET, POST, ...) as well as the special cases described above. Is this the way to go? Do you have any thoughts on this? And, last but not least: Do you think this feature is desirable and has a chance to be merged in the main Eve tree?

[1] https://github.com/dkellner/eve/tree/resource-specific-id-field

**Comment by nicolaiarocci** [comment]
>  And, last but not least: Do you think this feature is desirable and has a chance to be merged in the main Eve tree?

Absolutely. Actually, this is something I've been meaning to implement soon or later. I looked at your work and it looks rock solid and well thought (I also appreciate the little refactoring here and there).

> My next step would be to introduce a new resource in eve/tests/test_settings.py with a custom id field to be able to test the "standard" cases (like GET, POST, ...) as well as the special cases described above. Is this the way to go? 

Looks good to me.  Also make sure you update the documentation before submitting the PR.

Thanks!
