### ISSUE TITLE
unique constraint not working for bulk insert and multithreading

### ISSUE THREAD

**Issue by dkellner** [nicolaiarocci/eve#691]
The unique constraint is not working for bulk inserts and multihreading (like possible with WSGI-hosting), if there is no enforcement at the data layer.

Consider the following DOMAIN:
```python
DOMAIN = {
    'users': {
        'schema': {
            'firstname': {'type': 'string'},
            'lastname': {
                'type': 'string',
                'unique': True
            }
        }
    }
}
```

A POST using bulk insert will succeed:
```
curl -X POST -i -d '[{"firstname":"John","lastname":"Doe"},{"firstname":"Jane","lastname":"Doe"}]' -H 'Content-Type: application/json' http://eve-demo-app/users
```

Furthermore, I was able to create those two users in seperate requests when I added a time.sleep in methods/post.py after validation passes. This means that we can get race conditions even if no bulk inserts are involved.

I think one could solve the problem with bulk inserting, but I'm not sure about the second one. Is this solvable at the Eve level without support from the underlying database at all? If not, how reasonable is a unique constraint in the domain configuration?

**Comment by nicolaiarocci** [comment]
Yes this is also noted in the [documentation](http://python-eve.org/config) (see the note about bulk inserts and `unique` rule). 

On race condition on one document inserts, although very unlikely to happen, it is still a possibility. If this is a concern, one might opt for adding a unique index at the db level (especially so if that would also help with querying). 

I guess some work could be done on the server or even on a custom validation to mitigate the issue (a redis cache with recently added unique values?) but even then, you probably would not rule out the chance completely.

**Comment by dkellner** [comment]
Ah, sorry! I missed that part of the documentation.

I think database support for uniqueness is the best solution. Just wondering how well Eve communicates this as there is a possibility to specify 'unique' in the DOMAIN configuration - but with the drawbacks stated above. Maybe I'll change the documentation a little bit and send a PR to make this clear.
