### ISSUE TITLE
Support serialization inside Cerberus 0.9 new rules: anyof, oneof, allof, noneof

### ISSUE THREAD

**Issue by arnauorriols** [nicolaiarocci/eve#692]
The current implementation of the `eve.methods.common.serializer` is not aware of the new rules of Cerberus `anyof`, `oneof`, `allof` and `noneof`, resulting in fields defined inside any of this rules not getting (de)serialized.

**Comment by nicolaiarocci** [comment]
Thanks for reporting. Can you please PR a failing test, or just post an example snippet?
