### ISSUE TITLE
Exclusion projections can be overridden by request string

### ISSUE THREAD

**Issue by mmiz** [nicolaiarocci/eve#700]
I need to make some fields in my collection visible only for registered users.
So, i decided to make a public collection with projection:
partially_public_resource = {
    'datasource': {
        'projection': {
            'secret_field1: 0,
            'secret_field2': 0}
    },
'schema': {
'public_filed': {'type': 'string'},
'secret_filed1': {'type': 'string'},
'secret_filed2': {'type': 'string'}
}
Works as expected if you just query GET /partially_public_resource
But if you query GET /partially_public_resource?projection={"secret_field1": 1} it is returned in response.
Is there any way to force projections on server side?

**Comment by nicolaiarocci** [comment]
Do you actually need those fields in the schema? Since clients are not
supposed to consume them it might be worth it not adding them to the
schema. Or, if you actually want those fields for write-only operations,
you could setup a different endpoint for writes (you can set different API
endpoints to consume the same datasource).

Il giorno ven 4 set 2015 alle ore 18:26 mmiz <notifications@github.com> ha
scritto:

> I need to make some fields in my collection visible only for registered
> users.
> So, i decided to make a public collection with projection:
> partially_public_resource = {
> 'datasource': {
> 'projection': {
> 'secret_field1: 0,
> 'secret_field2': 0}
> },
> 'schema': {
> 'public_filed': {'type': 'string'},
> 'secret_filed1': {'type': 'string'},
> 'secret_filed2': {'type': 'string'}
> }
> Works as expected if you just query GET /partially_public_resource
> But if you query GET
> /partially_public_resource?projection={"secret_field1": 1} it is returned
> in response.
> Is there any way to force projections on server side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaiarocci/eve/issues/700>.
>
-- 
Nicola Iarocci
http://nicolaiarocci.com

**Comment by mmiz** [comment]
I need those fields to be visible/editable only for certain roles (admin) and they are intended to be used in business logic (which I planned to implement in pre_GET/POST events). So it is crucial to protect them.
I thought two collections, one public with projections and second full with restricted access would do the trick, but in turned out that projections could be easily overridden (what is not clear from the documentation).
Maybe it can be solved by moving those fields into separate document with restricted access (am i right that this would work as I described?), but in this case I'm forced by eve to split the document in two pieces in database.

**Comment by nicolaiarocci** [comment]
My suggestion would be one collection, two endpoints: one for your admin
roles with those fields, the other for the public with those fields
unmapped so they are never exposed.

Il giorno sab 5 set 2015 alle ore 17:00 mmiz <notifications@github.com> ha
scritto:

> I need those fields to be visible/editable only for certain roles (admin)
> and they are intended to be used in business logic (which I planned to
> implement in pre_GET/POST events). So it is crucial to protect them.
> I thought two collections, one public with projections and second full
> with restricted access would do the trick, but in turned out that
> projections could be easily overridden (what is not clear from the
> documentation).
> Maybe it can be solved by moving those fields into separate document with
> restricted access (am i right that this would work as I described?), but in
> this case I'm forced by eve to split the document in two pieces in database.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaiarocci/eve/issues/700#issuecomment-137963273>.
>
-- 
Nicola Iarocci
http://nicolaiarocci.com

**Comment by mmiz** [comment]
Sorry, i muddled the collections and endpoints. I mean the same thing, I tried to make two endpoints for one datasource. I do not get how to make fields "unmapped". Do i need to write two different schemas for each endpoint (one with extra fields)?

P. S. Nicola, thank you for your help and for the great library!

**Comment by nicolaiarocci** [comment]
Yes, you simply define two endpoints, each one with a with different schemas. See [how you can leverage the `datasource` setting](http://python-eve.org/config#multiple-api-endpoints-one-datasource) to acheive that. 

You can of course have one common base definition so you don't repeat yourself, something like:

    _common_schema: {
        'field1': ...,
        'field2': ...
     }

    admin_endpoint_schema: {   
        'admin_field1': ...,
        'admin_field2': ...
    }

    admin_endpoint_schema.update(_common_schema)
    user_endpoint_schema = _common_schema

You get the point.

**Comment by mmiz** [comment]
Thanks once again! Somehow I didn't realized that I can have several schemas for one collection in database.
