### ISSUE TITLE
Schema dependencies on sub-document fields is not working

### ISSUE THREAD

**Issue by gmauleon** [nicolaiarocci/eve#706]
I.e. failed in /eve/io/mongo/validation.py line 299 on default = self.schema[d].get('default')
Aka in this case d is in the form "field.subfield" and we are missing the whole split + parts mechanism present in cerberus.

I tried to fixed that by myself but failed, sorry :) 
Sample schema:
```javascript
schema = {                                                                                           
    'field1': {                                                                                      
        'type': 'dict',                                                                              
        'schema': {                                                                                  
            'subfield1': {                                                                           
                'required': False,                                                                   
                'default': 'one'                                                                     
            }                                                                                        
        },                                                                                           
        'required': False                                                                            
    },                                                                                               
    'field2': {                                                                                      
        'required': True,                                                                            
        'dependencies': {'field1.subfield1': ['one', 'two']}                                         
    }                                                                                                
}     
```

**Comment by gmauleon** [comment]
I investigate that a little bit more yesterday and wanted to shared my thoughts.
Disclaimer: I'm quite the noob in python and I miss the project  big picture so sorry for any dumb assumptions or statement...

So looking a bit more at the code and doing a couple of test, I think 'self.schema' when we hit the _validate_dependencies function, contains only the closest enclosing schema from the whole schema. Thus we are pretty much screwed if we want to test the default from fields possibly outside the scope.

So I was wondering, instead of doing all the 'find valid default' logic here, if we could like build (at init ??) a 'default_document' containing all the defaults value from the whole schema, so that we could have that as a base dict and then update it with the original and/or the updated document part before directly passing it to cerberus.

Sidenote, in the current implementation in case of update/replace the code looks like:
```
dcopy = None
        if self._original_document:
            dcopy = copy.copy(document)
            dcopy.update(self._original_document)
```
but shouldn't it be reversed ?
```
dcopy = None
        if self._original_document:
            dcopy = copy.copy(self._original_document)
            dcopy.update(document)
```

If 'document' is the update we want to apply it to the original right ?

Thanks.
Gael

**Comment by gmauleon** [comment]
A well dig out some more and found the modifications that "kinda break" that in the first place:
https://github.com/nicolaiarocci/eve/issues?utf8=%E2%9C%93&q=353

Really not as simple as I thought. And much more than I could fix without breaking anything as a new guy wanting to participate. At least I tried :)

My initial need was to have a required field depending on the value of another field.
Aka if field1 is A then field2 is required else not (fields being not at the same level in the schema).

Maybe there is another way to achieve this?

Thanks.

**Comment by nicolaiarocci** [comment]
Should be fixed now!

**Comment by gmauleon** [comment]
Thanks!
