### ISSUE TITLE
Handle exceptions when parsing settings.py

### ISSUE THREAD

**Issue by mandarvaze** [nicolaiarocci/eve#713]
I had a bad class/SQLAlchemy model. All I get is very generic ``ConfigException: DOMAIN dictionary missing or wrong. `` which is not at all helpful.

I had to put a trace and debug the code, when the following was printed on the debugger console.

    sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'xxxxx' could not find table 'xxxx' with which to generate a foreign key to target column 'id'

There was a typo, which I was able to quickly fix based on the above error, but getting this error itself was impossible in "normal" way.

While I came across this when using eve-sqlalchemy (as may be evident from the exception) the problematic code is in the flaskapp.py of eve. 
(*I had almost written a bug against eve-sqlalchemy, when further digging revealed that problem is in the eve code*)

Here is a possible fix.
Either we can print, or raise the exception. But ``pass`` in the ``except`` clause doesn't help anyone.
I'm not sure how you want to handle this, so not sending PR yet. Let me know, and I can send in the PR

``flaskapp.py``

```diff
*** 211,222 ****
              else:
                  abspath = os.path.abspath(os.path.dirname(sys.argv[0]))
                  pyfile = os.path.join(abspath, self.settings)
              try:
                  self.config.from_pyfile(pyfile)
!             except Exception as e:
!                 raise e
                  # assume an envvar is going to be used exclusively
                  pass

          # overwrite settings with custom environment variable
          envvar = 'EVE_SETTINGS'
--- 211,221 ----
              else:
                  abspath = os.path.abspath(os.path.dirname(sys.argv[0]))
                  pyfile = os.path.join(abspath, self.settings)
              try:
                  self.config.from_pyfile(pyfile)
!             except:
                  # assume an envvar is going to be used exclusively
                  pass

          # overwrite settings with custom environment variable
          envvar = 'EVE_SETTINGS'


```

**Comment by nicolaiarocci** [comment]
Hey thanks for this. Digging a little further would have showed that this has been [addressed](https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L227-L233) already on development branch. Relevant CHANGES line:

    +- Fix: some schema errors were not being reported as SchemaError exceptions
    +  A more generic 'DOMAIN missing or wrong' message was returned instead.

**Comment by mandarvaze** [comment]
Awesome.
Unfortunately I tested my proposed fix, only on my local setup, which had `pip install` ed version.
I guess if I had attempted PR, I would have noticed that this is already addressed.

Sorry for the trouble.
I'll be more careful next time onwards.

*So when is 0.6 releasing* ? ;)

**Comment by nicolaiarocci** [comment]
Next Week Unless Shit Happens™

Il giorno mer 16 set 2015 alle ore 10:01 Mandar Vaze <
notifications@github.com> ha scritto:

> Awesome.
> Unfortunately I tested my proposed fix, only on my local setup, which had pip
> install ed version.
> I guess if I had attempted PR, I would have noticed that this is already
> addressed.
>
> Sorry for the trouble.
> I'll be more careful next time onwards.
>
> *So when is 0.6 releasing* ? ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaiarocci/eve/issues/713#issuecomment-140660842>.
>
-- 
Nicola Iarocci
http://nicolaiarocci.com
