### ISSUE TITLE
Custom resources

### ISSUE THREAD

**Issue by istinspring** [nicolaiarocci/eve#717]
Hi, i tried to look into the docs/code and similar github issues, there are few discussions 
https://github.com/nicolaiarocci/eve/pull/32 and even examples like https://github.com/nicolaiarocci/eve/commit/f11db56c8d81f9496ab27516dd842b4991da20b9 but unfortunately i need something else and it can't be done by events and database hooks (i believe).

Sometimes you'll require to run complex aggregation queries over data stored into collection or maybe make a single view of data stored on few collections. I wonder is it possible to easily implement custom eve resource endpoint? I want same xml/json render as other endpoints, same auth rules if possible, rate limiting, schema etc.

And after few hour i resolved this issue but it looks like a dirty hack. Let's say i want to create endpoint/resource which would be "virtual".

Let's say i have DOMAIN defined like this:

```python
DOMAIN = {
    "data": {.....},  # defined schema etc
    "groupby": {},  # <-- this is purposed virtual resource (with current implementation it should be removed)
}
```

```groupby``` probably might have a schema as well just like any other resource to validate results and i guess only ['GET', 'OPTIONS'] available. I didn't implement schema validation yet, but hope it's not too difficult.

```python
from settings import db_connection

def group_by_distributor(resource, lookup):
    db = db_connection()
    pipeline = [
        {"$project": {"source": 1}},
        {"$group": {"_id": "$source", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}},
    ]
    items_per_source = db.command("aggregate", "data", pipeline=pipeline)
    response = {'items_per_source': list(items_per_source['result'])}
    return response
```

Next added function called "custom endpoint".

```python
def custom_endpoint(**lookup):
    """ Resource endpoint handler
    :param url: the url that led here
    """
    response = None
    method = request_method()
    if method in ('GET', 'HEAD'):
        response = group_by_distributor(resource, lookup)
    elif method == 'OPTIONS':
        send_response(None, (response,))
    else:
        abort(405)
    return send_response(None, (response,))
    # return send_response(resource, response) <- resource is not defined in current implementation
```

and add url rule as i work with flask

```python
    api = ApiFactory.get_instance()
    api.add_url_rule('/groups', 'groups',
                     view_func=custom_endpoint, methods=['GET', 'OPTIONS'])
```

And got results just like other eve endpoints.

```
<resource>
<items_per_source><_id>item1</_id><count>69873</count></items_per_source>
<items_per_source><_id>item2</_id><count>15848</count></items_per_source>
</resource>
```
I wish there could be native support. As far as i see url initialization is here: https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L157

```_init_url_rules_``` function add url rule for ```home_endpoint``` which is good example of integrated "custom endpoint"

```_add_resource_url_rules``` adding url rules for resources.

But it's simply impossible to pass different endpoint function for the resource:

```python
self.add_url_rule(item_url, endpoint, view_func=item_endpoint, methods=['GET', 'OPTIONS'])
```

Purposes for "custom virtual endpoints": 

+ only GET method
+ maybe link with main datasource http://python-eve.org/config.html#multiple-api-endpoints-one-datasource
+ define this kind of resource on DOMAIN ```{'data_groupby': {'custom_endpoint': 'endpoints.group.group_by_distributor'}, 'schema': {...}}```
+ can have defined schema to validate results

**Comment by istinspring** [comment]
related https://github.com/nicolaiarocci/eve/issues/208

**Comment by istinspring** [comment]
any comments?

**Comment by amagdas** [comment]
Hi, we managed situations like this by using a custom data layer for Eve and basically intercepting all the calls sent to mongo.
This allowed us to give custom implementation to `get` requests and customize what is returned.
A rough idea of how it's done: http://www.superdesk.org/en/site/news/48/Superdesk-server-architecture-overview.htm
Also, you can check the service layer implemented in https://github.com/superdesk/superdesk-core ,
specifically resource declaration: 
https://github.com/superdesk/superdesk-core/blob/master/superdesk/resource.py 
and service: 
https://github.com/superdesk/superdesk-core/blob/master/superdesk/services.py 
Custom data layer: 
https://github.com/superdesk/superdesk-core/blob/master/superdesk/datalayer.py

An example using this:
https://github.com/superdesk/superdesk/blob/master/server/apps/macros/macros.py#L24

**Comment by istinspring** [comment]
@amagdas thank you, got it.

**Comment by nicolaiarocci** [comment]
@amagdas super! If I ever get around to making a testimonials page on the eve website can I add Superdesk to the list?

**Comment by amagdas** [comment]
Yes, that would be great.

**Comment by istinspring** [comment]
@nicolaiarocci can you suggest the right approach? 

I see the main problem is:

https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L679

```python
                self.add_url_rule(item_url, endpoint, view_func=item_endpoint,
                                  methods=['GET', 'OPTIONS'])
```

You can't pass custom function for url.

**Comment by nicolaiarocci** [comment]
As discussed elsewhere, the plan is to add support for MongoDB Aggregation Framework to Eve readonly endpoints. If I understand well that's what you would need here. It is going to take a while before I can work on that feature though, but it is definitely on the todo list and planned for next major 0.7 release.

With this being said, you could simply add your own custom endpoint on top of Eve API surface, using Flask natively to do whatever you need to, running and returning mongo aggregations included. You could either register your own blueprint (see the [eve-docs](https://github.com/charlesflynn/eve-docs) extension for an example), or  you could just add endpoints on top of eve (see my [blog post](http://nicolaiarocci.com/building-custom-endpoint-handlers-with-eve/)).

**Comment by istinspring** [comment]
@nicolaiarocci thank you for suggestions! I'll take a look on blog post and eve-docs.
