### ISSUE TITLE
"Bulk insert"  reports HTTP 422

### ISSUE THREAD

**Issue by sibeliuscn** [nicolaiarocci/eve#720]
I built a list contains  a few record ,and  then perform a POST  ,but Eve responses me with HTTP 422 which as below  
########
HTTP/1.1 100 Continue
HTTP 1.0, assume close after body
HTTP/1.0 422 UNPROCESSABLE ENTITY
Content-Type: application/json
Content-Length: 311
Server: Eve/0.5.3 Werkzeug/0.10.4 Python/2.6.6
Date: Mon, 28 Sep 2015 09:11:56 GMT
##########

in the other hand ,I checked and verified the backend MongoDB is ok for bulk insert with a list ,see below:
#########333
> db.vser.insert(list)
BulkWriteResult({
	"writeErrors" : [ ],
	"writeConcernErrors" : [ ],
	"nInserted" : 4, 
#############

**Comment by nicolaiarocci** [comment]
422 usually means a validation error. Check the response body to see which message is sending back to you.

**Comment by sibeliuscn** [comment]
It is fixed now ,if there are some documents contained errors in a bulk operation, this failure will occurs，tks you ：）
