### ISSUE TITLE
field filter didn't works 

### ISSUE THREAD

**Issue by sibeliuscn** [nicolaiarocci/eve#721]
"sort" and "projection" works fine like this : 
EVE:8888/projection={"CumReq":1,"Task":1,"node":1,"Run_queue":1,"tsid":1}&sort=tsid,-Run_queue

but "filter" didn't works: EVE:8888/someendpoint?where={"field-1":"xxx"}  

In guider,filter is enable in every field by default,how can i troubleshooting this ? check which configuration of which backend log?

**Comment by nicolaiarocci** [comment]
I am sorry but I can't understand what exactly your issue with. I'm going to close this but feel free to elaborate anyways.
