### ISSUE TITLE
Projection: Explicitly defined inclusions faulty

### ISSUE THREAD

**Issue by kenmaca** [nicolaiarocci/eve#722]
I'm trying to make use of projections on one of my endpoints named `user` to only show `username`s:

    config = {
        'item_title': 'user',
        'public_methods': ['POST'],
        'public_item_methods': [],
        'datasource': {
            'projection': {
                'username': 1
            }
        },
        'allowed_filters': [],
        'extra_response_fields': ['username'],
        'item_methods': ['GET', 'PATCH', 'DELETE'],
        'resource_methods': ['GET', 'POST'],
        'schema': schema
    }

This doesn't work and it exposes all fields as if I didn't specify the projection. If I change `'username': 0`, then for some reason it'll properly exclude just `username`. I thought a inclusion projection *only* exposed the fields that you define and hides the others? Strangely, if I pass the projection via URL (`users?projection={"username": 1}`) -- inclusion works as intended.

**Comment by kenmaca** [comment]
I should also mention that inclusion works fine on an endpoint that uses another collection via `source`.

**Comment by nicolaiarocci** [comment]
thanks for reporting!

**Comment by nicolaiarocci** [comment]
Should be fixed now!

**Comment by kenmaca** [comment]
Thanks!
