### ISSUE TITLE
Validating the where clause in Filtering

### ISSUE THREAD

**Issue by stratosgear** [nicolaiarocci/eve#728]
I have a use case where I would like the ?where= statement on a GET request be validated against the Resource schema and, obviously, fail if the validation does not pass.

I've posted a StackExchange question:

http://stackoverflow.com/questions/32611654/in-python-eve-how-do-i-validate-the-where-clause

but I didn't receive any valuable feedback, except for the fact that I can **manually** implement it through a hook event.

I find such functionality essential to Eve (well, at least if you ask **me**).  

First off, is something similar offered already, that I have overlooked?

And second, is it something that is worth creating a PR for...? Maybe by providing a setting if you want the where to be validated...?  I'd hate to cook something and then never have it merged. :)

**Comment by nicolaiarocci** [comment]
> I find such functionality essential to Eve (well, at least if you ask me).

I guess it could be a nice feature to have.

> First off, is something similar offered already, that I have overlooked?

No.

> And second, is it something that is worth creating a PR for...? Maybe by providing a setting if you want the where to be validated...? I'd hate to cook something and then never have it merged. :)

Yes, thanks, let's see what you come up with. I'm more than willing to review and assist. I'm not sure a setting would be necessary, but certainly it cannot be a bad thing and it would have very little impact so go for it.
