### ISSUE TITLE
Quickstart instructions produce 500 error

### ISSUE THREAD

**Issue by einchance** [nicolaiarocci/eve#745]
Following the documentation, I get 500 errors when following the quickstart instructions for http://127.0.0.1:5000/people with version 0.6.0.

After some investigation, it was because I did not have mongo up and running.

**Comment by nicolaiarocci** [comment]
Could you please switch DEBUG mode on (add `DEBUG=True` in settings.py) and post the stack trace you are getting? Thanks.

**Comment by einchance** [comment]
The issue was that I did not have mongo running when I attempted running 0.6.0.

**Comment by nicolaiarocci** [comment]
Ah ok. I should probably add a note about that. I've been falling to that myself :smile:
