### ISSUE TITLE
Would like to use ujson

### ISSUE THREAD

**Issue by valerierose** [nicolaiarocci/eve#751]
I've found that the json module choice can have a significant impact on the performance of an API when your use case requires serving up some big json. The ujson module performs significantly better than the simplejson module. It would be nice to be able to configure Eve to use ujson instead of simplejson. Or even if Eve were just switched from simplejson to ujson.

**Comment by julianhille** [comment]
Hey,

i wouldn't recommend in using that actually.
We used it and its faster BUT
- it fails in converting big numbers (of course you could fork and add that feature):

```
>>> ujson.dumps({'a': 2**62})
'{"a":4611686018427387904}'
>>> ujson.dumps({'a': 2**63})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: long too big to convert
```

vs 
```
>>> import simplejson
>>> simplejson.dumps({'a': 2**63})
'{"a": 9223372036854775808}'
```
-  it is not able to have custom Encoder/Decoder as simplejso and Eve makes use of that.

At least ujson just decodes sets to lists but simplejson does not.

Just pointing out some differences and issues.

**Comment by pfreixes** [comment]
I didn't try it, but it performs a bit beter than other implementations as I can see here [1]. Aside of the issues commented by @julianhille, in Eve paradigm it would be appreciable only with really big JSON objects such as resource results or long long items.


[1] http://blog.dataweave.in/post/87589606893/json-vs-simplejson-vs-ultrajson

**Comment by nicolaiarocci** [comment]
[This](https://github.com/esnme/ultrajson/issues/185) thread doesn't really help in making me want to adopt ujson. Codebase was last updated seven months ago and they do not seem to have access to the PyPy package anymore. Also, as showed by @julianhille and hinted in that thread, there are open issues which are not being addressed. Gains would also be marginal for most use cases, so I do not think we should go this path anytime soon.
