### ISSUE TITLE
Where is request_method from utils?

### ISSUE THREAD

**Issue by istinspring** [nicolaiarocci/eve#753]
https://github.com/nicolaiarocci/eve/blob/develop/eve/utils.py

```text
    from eve.utils import request_method, parse_request
ImportError: cannot import name request_method
```

**Comment by nicolaiarocci** [comment]
Removed with 9b54313206f1f10ba19e1ffa591875095f81e3cb. Relying on flask `request.method` now that we are using Flask middleware for parsing `X-HTTP-Method-Override`. And yes, should probably have mentioned the removal in the changelog, sorry about that.

**Comment by istinspring** [comment]
No problems it's relatively minor thing, i got error because i "hacked" eve to make custom endpoints with aggregation. 

Thank you for the explanation!
