### ISSUE TITLE
JSON output with unicode escapes character

### ISSUE THREAD

**Issue by mion00** [nicolaiarocci/eve#754]
Hy @nicolaiarocci. Thank you for this amazing project! I am building a RESTFUL backend for a group project with Eve and it's really easy to get up and running, once you know the basic steps.

I found out that the JSON returned by Eve (having disabled xml with the option "XML=False") is composed by escaped Unicode character. This cannot be properly shown in a browser, given that the content/type "appliation/json" is supposed to have UTF-8 as its character encoding.
![screenshot from 2015-11-04 00 53 16](https://cloud.githubusercontent.com/assets/4510647/10925469/b4e3b244-828e-11e5-9ccf-a43b6de8946b.png)

I googled a bit and came to the conclusion that the function json.dump(), used in renderer.py is responsible for this. By default its escapes every non ASCII character in Unicode escape sequence, creating the problem I found. 
Changing the parameter "ensure_ascii" to False solves this problem.
![selection_004](https://cloud.githubusercontent.com/assets/4510647/10925528/3e17e102-828f-11e5-9fbe-5cb12fe0638f.png)

**Comment by nicolaiarocci** [comment]
Looks like the browser does not handle the UTF-8 correctly. Same json is properly parsed by curl or even Chrome with Postman. It is actually rare that you have to display the json directly in a browser, what is your use case?

**Comment by mion00** [comment]
My fault! I was using the browser just for quick debugging purposes. I thought that it could correctly display JSON data, but I was proven wrong. Using curl or Postman, as you said, correctly display the characters.
