### ISSUE TITLE
Delegate Search to Elasticsearch

### ISSUE THREAD

**Issue by reallyangrydude** [nicolaiarocci/eve#755]
Hi,

I am running Eve with a Mongo database, which I have converted to a replica set; this lets me use richardwilly98's elasticsearch river (https://github.com/richardwilly98/elasticsearch-river-mongodb) to index the database.  However, I would now like to delegate the search in Eve to use the elasticsearch that I have running.  Is there a way to do this?

Thanks!

**Comment by nicolaiarocci** [comment]
Hello, have you checked [Eve-Elastic](https://github.com/petrjasek/eve-elastic) yet?

**Comment by kalbasit** [comment]
Hi @nicolaiarocci, as I understand Eve-Elastic, it's supposed to replace Mongo as the backend. We are looking for delegating the search feature to ElasticSearch. Is it possible to dynamically switch the backend used depending on the action performed?

**Comment by nicolaiarocci** [comment]
Nope and I agree that it would be a nice super-feature to have :)

**Comment by amagdas** [comment]
@kalbasit actually you can use Eve-Elastic side-by-side with Mongo, you just have to create a custom Eve datalayer like this one: https://github.com/superdesk/superdesk-core/blob/master/superdesk/datalayer.py

**Comment by kalbasit** [comment]
@amagdas oh cool, nice one.. We'll try it out.
