### ISSUE TITLE
Simple example breaks on GET of /people

### ISSUE THREAD

**Issue by jeroenes** [nicolaiarocci/eve#757]
Thanks to all contributors for making this great framework. Really an excellent way to write a RESTful interface!

After making a post in the mailing list (https://groups.google.com/forum/m/#!topic/python-eve/zy9x2CTubek) I discussed it briefly on IRC. There some figured it liked a problem in the recent versions of eve. Now it seems a better idea to post this as an issue.

Here it goes: Testing the trivial Eve-sqlalchemy example I get an exception when requesting with 
     curl 127.0.0.1/people
OperationalError: (sqlite3.OperationalError) no such column: People [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT People) AS anon_1']

It even fails with the simplest eve program (the one in http://python-eve.org/quickstart.html):
TypeError: __init__() got an unexpected keyword argument 'fields'

I can get a valid response with 'obama' in the slightly expanded example. I have not succeeded in getting a meaningful response out of the trivial sqlalchemy example at all unfortunately.

Please let me know if you need more information to replicate this behavior. And thanks for any advice or help that you may be able to provide!

Best regards, 
Jeroen

**Comment by nicolaiarocci** [comment]
Hello, please move this to the [Eve-SQLAlchemy](https://github.com/RedTurtle/eve-sqlalchemy/issues) ticket system. I'm sure they will help you out!

**Comment by jeroenes** [comment]
I will put it there, but do I need the split the issue than? The pure eve example fails as well, see above.

Cheers,
Jeroen
