### ISSUE TITLE
Is it possible to disable metadata (i.e. etag & created)

### ISSUE THREAD

**Issue by waynew** [nicolaiarocci/eve#759]
I was experimenting with eve-sqlalchemy and ran into an issue where [I was missing metadata columns](https://github.com/RedTurtle/eve-sqlalchemy/issues/83) in my models.

We've been looking at Eve as a way to expose some of our (postgresql) data via API, but when it comes to *inserting* data, I'd rather not have to add extra columns to all of our tables. I searched around in the documentation for this ability and wasn't able to find anything. I did find where you could change the columns, so we can use our own ID column, and with my little experiments that worked fine. But trying to set `ETAG = None`, etc. appeared to have no effect.

Is it *possible* to disable the metadata feature - at least for certain resources (is that the right term?)?

**Comment by nicolaiarocci** [comment]
> Is it possible to disable the metadata feature - at least for certain resources (is that the right term?)?

I am afraid not as those fields are vital to most API functionality.
