### ISSUE TITLE
The simplest Eve example program breaks on its collection endpoint

### ISSUE THREAD

**Issue by jeroenes** [nicolaiarocci/eve#760]
The simplest Eve example program fails (the one in http://python-eve.org/quickstart.html):
`TypeError: init() got an unexpected keyword argument 'fields'`

I can get a valid response with 'obama' in the slightly expanded example, so it seems it has to do something with how the collection endpoint is handled. I can also confirm that the example does run as advertised after downgrading to Eve 0.5.3

Please let me know if you need more information to replicate this behavior. 

Best regards,
Jeroen

**Comment by nicolaiarocci** [comment]
Just tested with a fresh virtualenv with Eve 0.6.1 installed. It runs without glitches up until the "database interlude paragraph" (which I did not test). Are you using the correct version for all requirements?

**Comment by jeroenes** [comment]
You are right. This goes away with a fresh virtualenv. I did not save the exact environment before I downgraded to Eve 0.5.3 and I cannot reproduce this error myself! Probably something wrong in the way I used pip or something like that. (It did not affect my original sqlalchemy problem though ;-( )

Excuse me for not checking fully.

**Comment by nicolaiarocci** [comment]
Glad that we sorted it out :+1:
