### ISSUE TITLE
How to do route redirect ?

### ISSUE THREAD

**Issue by cadesalaberry** [nicolaiarocci/eve#765]
Here is my sample code. I assumed it would work like flask:

```python
from eve import Eve
app = Eve()

@app.route('/search')
def function():
  print 'Should return all restaurants for now'
  return redirect(url_for('/restaurants'))

if __name__ == '__main__':
    app.run()
```

The `Should return all restaurants for now` gets printed to the console, but it leads to a 500:

```bash
$ curl localhost:5000/search
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

It tells me that `NameError: global name 'redirect' is not defined`

There must be a way, but I could not find it in the documentation available online. What would be the equivalent for eve ?

**Comment by nicolaiarocci** [comment]
Try the following:

```py
from flask import redirect
from eve import Eve
app = Eve()

@app.route('/search')
def function():
  return redirect('/restaurants')

if __name__ == '__main__':
    app.run()
```

Please use StackOverflow for usage/help requests (use the `eve` tag which is being monitored), or the mailing list. This is reserved to bug and feature requests. Thanks!

**Comment by cadesalaberry** [comment]
Thanks, worked wonderfully, sorry for the noise.
