### ISSUE TITLE
TypeError: datetime.time(0, 15) is not JSON serializable

### ISSUE THREAD

**Issue by johnnywell** [nicolaiarocci/eve#770]
I'm having this error when trying to get some objects from a Firebird Database. Is it related to DATE_FORMAT or it should serialize any datetime object?

Following the traceback:
https://gist.github.com/anonymous/fafe8dc7b8d8da14dd24

**Comment by nicolaiarocci** [comment]
I assume you are using Eve-SQLAlchemy extension. Please open a ticket at the [Eve-SQLAlchemy page](https://github.com/RedTurtle/eve-sqlalchemy/issues).
