### ISSUE TITLE
Global ITEM_URL not working

### ISSUE THREAD

**Issue by ralphsmith80** [nicolaiarocci/eve#785]
I've got a very simple setup using eve and eve_sqlalchemy to connect to a Postgres database. I've been able to GET items with UUID id fields using `'item_url': 'regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")'` at the DOMAIN level but the global `ITEM_URL` is not getting picked up.

Below are examples of configs that I've used with `item_url` that work and configs with `ITEM_URL` that do not work. Since I'm playing with laying this on top of an existing database it would be really nice to be able to use the global `ITEM_URL` setting.

**Versions**
`eve_sqlalchemy-0.4.2`
`eve-0.6.1`

**Setting item_url at the resource level that works**
```settings.py
from eve.utils import config

ID_FIELD = 'id'
ITEM_LOOKUP_FIELD = ID_FIELD
config.ID_FIELD = ID_FIELD
config.ITEM_LOOKUP_FIELD = ID_FIELD

DOMAIN = {
    'people': People._eve_schema['people'],
}
DOMAIN['people'].update({
    'item_title': 'people',
    'item_url': 'regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")',
    },
})
```
or
```settings.py
DOMAIN = {
    'people': People._eve_schema['people'],
}
DOMAIN['people'].update({
    'additional_lookup': {
        'url': 'regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")',
        'field': 'id'
    },
})
```

**Setting ITEM_URL at the Global level that does not work**
```settings.py
from eve.utils import config

ID_FIELD = 'id'
ITEM_LOOKUP_FIELD = ID_FIELD
config.ID_FIELD = ID_FIELD
config.ITEM_LOOKUP_FIELD = ID_FIELD

ITEM_URL = 'regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")'
```
or
```settings.py
from eve.utils import config

ID_FIELD = 'id'
ITEM_LOOKUP_FIELD = ID_FIELD
config.ID_FIELD = ID_FIELD
config.ITEM_LOOKUP_FIELD = ID_FIELD

ITEM_URL = 'regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")'
config.ITEM_URL = ITEM_URL
```

**Complete settings.py**
```settings.py
from eve.utils import config
from eve_sqlalchemy.decorators import registerSchema
from tables import People

ID_FIELD = 'id'
ITEM_LOOKUP_FIELD = ID_FIELD
config.ID_FIELD = ID_FIELD
config.ITEM_LOOKUP_FIELD = ID_FIELD

registerSchema('people')(People)

SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres@localhost/people'

ITEM_URL = 'regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")'

DOMAIN = {
    'people': People._eve_schema['people'],
}
```

**error response**
```
{ "_error" : { "code" : 404,
      "message" : "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."
    },
  "_status" : "ERR"
}
```

**Comment by ralphsmith80** [comment]
Just to add a little more info. I printed out `app.config['ITEM_URL']` just before `app.run()` and the value of `ITEM_URL` from my settings.py is getting set i.e.
```
app.config['ITEM_URL'] == regex("[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}")
```
Just isn't being honored.

**Comment by nicolaiarocci** [comment]
Hello, Please move this to the [Eve-SQLAlchemy](https://github.com/RedTurtle/eve-sqlalchemy/issues) repository.

**Comment by ralphsmith80** [comment]
The issue is with Eve. The endpoint is not being properly defined. I'm still debugging Eve but the issue is in [flaskapp.py here](https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L715). 

The `item_url` still being set to `/people/<regex("[0-9]+"):id>`.

**Comment by ralphsmith80** [comment]
When register_resource is invoked [here](https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L175) there is already a `item_url` setting so `setdefault` [here](https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L541) here as no effect. The default `ITEM_URL` will never be used.

**Comment by ralphsmith80** [comment]
Here's the related issue. RedTurtle/eve-sqlalchemy#68

**Comment by nicolaiarocci** [comment]
:+1:
