### ISSUE TITLE
How to define a custom filter and bind it to a resource endpoint

### ISSUE THREAD

**Issue by m3talstorm** [nicolaiarocci/eve#789]
I'm using Python EVE, EVE-SQLALchemy, Flask, Flask-SQLALchemy, SQLALchemy and a Postgres database.

I have my API endpoints all setup and they are working fine out the box.

Now i'm trying to filter the items returned by the some_model resource so that it only returns items (GET) that belong to a certain user (the user doing the API request) or have a certain name (prefix). The SQlAlcehmy code to perform this is below:

    session.query(SomeModel).filter(or_(SomeModel.name.like('SOMETHING_%'), SomeModel.account_id==1)).all()

I've looked at pre and post request hooks, User-Restricted Resource Access and everything else I could find, but nowhere seems to describe how to apply custom filters to (all) GET requests of a certain endpoint/resource.

Kind of like the URL filter functionality, but always on and filtering at the database level, not the serialization/response level.

**Comment by nicolaiarocci** [comment]
This seems not related to Eve-core, so please move this to the [Eve-SqlAlchemy](https://github.com/RedTurtle/eve-sqlalchemy/issues) ticket system.
