### ISSUE TITLE
SCHEMA_ENDPOINT option does not work when schema has lambda coerce function.

### ISSUE THREAD

**Issue by gwainer** [nicolaiarocci/eve#790]
My Cerberus schema has in it a structure like this (irrelevant parts omitted):
```python
to_bool = lambda v: v if type(v) is bool else v.lower() in ['true', '1']

schema = {
(...)
    'promotional_emails': {
        'type': 'boolean',
        'coerce': to_bool,
        'default': False
    },
(...)
}
```
I noticed that when I tried to set the SCHEMA_ENDPOINT option in settings.py with this schema, I got an error due to the `to_bool` function is not serializable. Partial error log below:

```python
  File "/Users/g/.virtualenvs/api-env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 43, in default
    return super(MongoJSONEncoder, self).default(obj)
  File "/Users/g/.virtualenvs/api-env/lib/python3.5/site-packages/eve/io/base.py", line 36, in default
    return json.JSONEncoder.default(self, obj)
  File "/Users/g/.virtualenvs/api-env/lib/python3.5/site-packages/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x10df32510> is not JSON serializable
```
If I comment the `coerce` part from schema it works OK.

**Comment by nicolaiarocci** [comment]
Yes this happens because JSON can't serialize a lambda. This should only be a concern when exposing resource schema through the `SCHEMA_ENDPOINT` feature. As I see it we have two options here:

1. Do not expose `coerce` rule with the resource schema (it's internal stuff after all)
2. Customize `JSONEncoder` and replace the lambda with some constant value like "a callable".

I like the first option a lot more. Thoughts?

**Comment by gwainer** [comment]
Yes, agree with option 1. I will try to submit a pull request when I got the the time if not fixed until then.

**Comment by nicolaiarocci** [comment]
Went with option #1 for the time being. #2 seemed overcomplicated for such a marginal issue. Feel free to PR for it if you have the time/feel like improving this.

**Comment by gwainer** [comment]
Thank You!
