### ISSUE TITLE
Suggestion: Clarify Documentation for Custom Validators

### ISSUE THREAD

**Issue by adityaramesh** [nicolaiarocci/eve#796]
Hello everyone,

I'm using eve 0.6.1, and needed to write a custom validator for POST and PATCH requests. To do this, I derived from `eve.mongo.io.Validator`. I noticed that while `validate` is called after POST requests, it is not called not after PATCH requests. Despite fact that the [Cerberus documentation](https://github.com/nicolaiarocci/cerberus/blob/master/cerberus/cerberus.py#L161) indicates that `validate_update` is deprecated in favor of `validate` with `update=True`, the `Validator` class in the `eve.mongo.io` namespace still uses a function called `validate_update` to process PATCH requests. So in fact, both `validate` and `validate_update` need to be overridden. I think this is misleading, and warrants some clarification in the documentation for Eve.

**Comment by nicolaiarocci** [comment]
Eve is still using the now deprecated `validate_update` method. The plan is to update Eve 0.7 to support Cerberus 1.0 (which is not released yet). When we do that we also drop the deprecated code.

**Comment by nicolaiarocci** [comment]
Related to #776
