### ISSUE TITLE
validator schema not needed but fails

### ISSUE THREAD

**Issue by julianhille** [nicolaiarocci/eve#797]
The validator class in eve.io.mongo.validation has an inconsistency in its requirements:
```
 def __init__(self, schema=None, resource=None, allow_unknown=False,
                 transparent_schema_rules=False):

```

States that schema defaults to None and is not required.
```
self = <play.api.application.Validator object at 0x1081a7eb8>, schema = None

    def _remove_unique_rules_on_fields_with_unique_index(self, schema):
        # TODO: Actually do what the function name suggests. This version just
        # removes the unique constraint on _id. We could use the information
        # available by app.data.driver.db[datasource].index_information() to
        # remove all unnecessary unique constraints.
        result = copy.deepcopy(schema)
>       if '_id' in result and 'unique' in result['_id']:
E       TypeError: argument of type 'NoneType' is not iterable
```

So two ways of fixing that from here imho
1. make schema a  required parameter
2. ignore schema if None in _remove_unique_rules_on_fields_with_unique_index

**Comment by nicolaiarocci** [comment]
Thanks for reporting this. I would go with option 2.

**Comment by julianhille** [comment]
I will send a PR later this evening.

Nicola Iarocci <notifications@github.com> schrieb am Mi., 6. Jan. 2016
18:24:

**Comment by nicolaiarocci** [comment]
Thanks for the PR. Keeping this on hold until we sort out the fate of #788.

**Comment by julianhille** [comment]
im fine with that.

**Comment by nicolaiarocci** [comment]
At first glance I'd say that since last commit (8e2e17d3e02c3c0a95a5f417fcf6cf5a36cd8dc3) this should not be needed anymore. Can you please confirm? Thanks!

**Comment by julianhille** [comment]
yes that will fix it.
