### ISSUE TITLE
Small bug in documentation for event hooks

### ISSUE THREAD

**Issue by adityaramesh** [nicolaiarocci/eve#798]
In the documentation for [post-update hooks](http://python-eve.org/features.html#database-event-hooks)  (see the row in the table for "Update", "Item", and "After"), I think the parameter `updated` should be renamed to `update`. This parameter actually seems to be a dict of the updates applied to the original document, rather than the updated version of the document itself.

I can submit the patch to make this chance in the docs, but can someone more experienced with Eve confirm this?

**Comment by nicolaiarocci** [comment]
Looks good, I'd call it `updates`.
