### ISSUE TITLE
PUT method for nonexistent document is not working (404 error)

### ISSUE THREAD

**Issue by jonataa** [nicolaiarocci/eve#803]
Hey guys,

I'm having problems with PUT methods for nonexistent document. I am getting 404 error with ```UPSERT_ON_PUT = True```.

cURL command:
```shell
curl -X PUT http://127.0.0.1:5000/persons/0 -d '{"firtname":"Black", "lastname":"White"}'
```
Output:
```shell
{"_status": "ERR", "_error": {"message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.", "code": 404}}
```

That's my settings file.
```python
(...)

IF_MATCH = False
ITEM_METHODS = ['PUT']
UPSERT_ON_PUT = True

persons = {
    'schema': {
        'firstname': {
            'type': 'string'
        },
        'lastname': {
            'type': 'string'
        }
    }
}

DOMAIN = {
    'persons': persons
}
```
[Full source code](https://gist.github.com/jonataa/aa1268aea065052b7f5a)

Does anyone are having this problem?

Thanks,

Jonata Weber

**Comment by nicolaiarocci** [comment]
What kind of id field are you using? Looking at the url it looks like you are not using `ObjectId`, which is the default.

**Comment by jonataa** [comment]
You're right! I tried with an object id fake and it has worked as expected. Thanks a lot! But how to use ```lastname``` field as an additional lookup?

I'm doing this way and getting 404 error. 

```shell
http GET localhost:5000/persons/bar
```

```python
persons = {
    'schema': {
        'additional_lookup': {
         'url': '[\w]+',
         'field': 'lastname',
        },
        'firstname': {
            'type': 'string'
        },
        'lastname': {
            'type': 'string',
            'unique': True
        }
    }
}
```

my collection
```mongodb
{
  "_id": ObjectId("56990531decc7bdf21d5303f"),
  "firstname": "foo",
  "lastname": "bar"
}
{
  "_id": ObjectId("56990906decc7bdf21d53040"),
  "firstname": "fizz",
  "lastname": "buzz"
}
```

Thanks in advance!

JW

**Comment by nicolaiarocci** [comment]
Try the following:

    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'lastname'
    }

**Comment by jonataa** [comment]
Its works! Thank you! The code snippet of tutorial is wrong:

```python
accounts = {
     # the standard account entry point is defined as
     # '/accounts/<ObjectId>'. We define  an additional read-only entry
     # point accessible at '/accounts/<username>'.
     'additional_lookup': {
         'url': '[\w]+',
         'field': 'username',
     },
(...)
```
From: http://python-eve.org/tutorials/account_management.html#b-user-roles-access-control

**Comment by nicolaiarocci** [comment]
Ah right, we did not update the docs when we changed that behaviour. Good catch.

**Comment by nicolaiarocci** [comment]
Should be fixed. Thanks.
