### ISSUE TITLE
EVE can not load utf-8 settings.py file.

### ISSUE THREAD

**Issue by hyacinthus** [nicolaiarocci/eve#805]
EVE can not start If there is a non-ascii character: 
```python
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    app = Eve()
  File "/home/crandom/eve/eve/flaskapp.py", line 138, in __init__
    self.load_config()
  File "/home/crandom/eve/eve/flaskapp.py", line 233, in load_config
    self.config.from_pyfile(pyfile)
  File "/home/crandom/dev/lib/python3.4/site-packages/flask/config.py", line 129, in from_pyfile
    exec(compile(config_file.read(), filename, 'exec'), d.__dict__)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 2840: ordinal not in range(128)
```

My interpreter is python 3.4

**Comment by nicolaiarocci** [comment]
See if this can help https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by hyacinthus** [comment]
It is so strange...
In my Mac OS and Ubuntu, I connect to my cloud server by ssh in terminal, this error appears..
But I connect to it by Windows Xshell, everything is OK...

locale is the same, python is the same, env is same...

I'll have more test.

**Comment by hyacinthus** [comment]
Resolved,  problem is here:
http://www.cyberciti.biz/faq/os-x-terminal-bash-warning-setlocale-lc_ctype-cannot-change-locale/
ssh will send local LC_* to remote.
