### ISSUE TITLE
Support dot notation for field name in sub-resources regex

### ISSUE THREAD

**Issue by mcreenan** [nicolaiarocci/eve#808]
I'm trying to start using the sub-resources feature and ran into a slight inconvenience.

I have a resource called `events` which uses the default `_id`.

I also have a resource called `suite_events` which I tried to add field called `event` which is a dict, then a field under that called `_id` which is an objectid and has a data relation to collection `events` field `_id`

Finally, I set the `url` config on the `suite_events` resource to this:
```
        'url': 'events/<regex("[a-f0-9]{24}"):event._id>/suites',
```

However, this errors with
```
ValueError: malformed url rule: '/events/<regex("[a-f0-9]{24}"):event._id>/suites'
```

Any chance the dot notation could be allowed within the regex?

**Comment by nicolaiarocci** [comment]
This is a Flask/Werkzeug issue. To my knoweldge, it is not possible to use dot notation when setting up the regex for url rules. And sorry for getting back to you so late.
