### ISSUE TITLE
on_post_POST_<resource> does not have "_id" field in the response

### ISSUE THREAD

**Issue by fsiddi** [nicolaiarocci/eve#813]
Given the following snippet: 
```
def post_POST_projects(request, payload):
    print(request.get_json())

app.on_post_POST_projects += post_POST_projects
```

In eve 0.5.3 it returned all fields of the newly created object, in our case:

```
{
'_updated': datetime.datetime(2016, 1, 22, 18, 51, 59), 
'_id': ObjectId('56a27a4fd1b8fc02caf51e5a'), 
'_created': datetime.datetime(2016, 1, 22, 18, 51, 59),
'_status': 'OK',
'_etag': 'f2ac49d98e0284df4cb06f57e3a7fe30df05d464',
u'name': u'My project',
u'user': ObjectId('552b066b41acdf5dec4436f2'),
u'backend': u'gcs'
}
```

In eve 0.6 it does not return fields starting with `_`

```
{
u'name': u'My project',
u'user': ObjectId('552b066b41acdf5dec4436f2'),
u'backend': u'gcs'
}
```

Is it a known issue? I looked at commit logs but could not find an answer.

**Comment by nicolaiarocci** [comment]
Hello,

you should be printing `payload.get_data()` instead, as `request` contains the request sent from the client to server, hence it lacks the API metadata fields. `payload` on the other hand is the server response.

def post_POST_projects(request, payload):
    print(payload.get_data())

app.on_post_POST_projects += post_POST_projects

Home this helps.

**Comment by fsiddi** [comment]
Hi,
thanks a lot for the hint! It totally makes sense.
