### ISSUE TITLE
POST got 400 error when JSON string contains ISODate

### ISSUE THREAD

**Issue by soyoeml** [nicolaiarocci/eve#817]
Hi,

I got a very strange issue. Please see this command:
`curl  -H "Content-Type:application/json" -d '{ "serialnumber" : "1", "site" : "87", "timetaken" : "00:11:29", "errorCode" : "1", "portNumber" : "4", "operator" : "930", "serverTime" : ISODate("2014-10-08T03:52:26Z"), "ErrList" : "0", "iosVersion" : "8.0.2",  "sourceModel" : "iPhone5sGSM", "StartTime" : "2014-10-09 00:45:34" }'  http://10.1.2.188/transaction_p
`
Result
`{"_status": "ERR", "_error": {"message": "The browser (or proxy) sent a request that this server could not understand.", "code": 400}}`

But if I removed ""serverTime" : ISODate("2014-10-08T03:52:26Z"),", it works great. Any idea?

My eve version: 0.7
settings.py
-----------------------------------------------------------------------------------------
import os

MONGO_HOST = os.environ.get('MONGO_HOST', 'localhost')
MONGO_PORT = os.environ.get('MONGO_PORT', 27017)
MONGO_USERNAME = os.environ.get('MONGO_USERNAME', '*****')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', '*****')
MONGO_DBNAME = os.environ.get('MONGO_DBNAME', 'testdb')

RESOURCE_METHODS = ['GET','POST']

ITEM_METHODS = ['GET', 'PATCH'] 

CACHE_CONTROL = 'max-age=20'
CACHE_EXPIRES = 20

DEBUG = True
ALLOW_UNKNOWN = True
ITEM_URL =  'regex("[\w]+")' 

transaction_p = {}

DOMAIN = {'transaction_p':transaction_p}
------------------------------------------------------------------------------

**Comment by petrjasek** [comment]
hi, there is no such thing as `ISODate` in json, that's the issue. so in your json it should be like:
```
"serverTime" : "2014-10-08T03:52:26Z"
```

**Comment by soyoeml** [comment]
OK. Thanks

It should be  "serverTime" : { "$date" : "2014-10-08T17:57:20.182Z"}
