### ISSUE TITLE
Allow disabling entry point semantics for HATEOAS

### ISSUE THREAD

**Issue by vfaronov** [nicolaiarocci/eve#818]
This is to some degree a rehash of #473, but I’d like to raise a new point.

> HATEOAS links are always relative to the API entry point, so if your API home is at `examples.com/api/v1`, the `self` link in the above example would mean that the _people_ endpoint is located at `examples.com/api/v1/people`.

This greatly reduces the potential usefulness of HATEOAS, because it requires the client to have application-specific, out-of-band knowledge (the API entry point) in order to resolve the URLs.

This is becoming important due to the rise of standardized hypermedia formats like [HAL](http://stateless.co/hal_specification.html) (very similar to Eve’s default HATEOAS format). A client coded against HAL might be seeded with a start URL and then follow a chain of links to other resources, possibly located on other servers. Eventually it may navigate to a resource that is served by Eve—but it knows nothing about Eve or its entry points, all it knows is the request URL. For the client to keep going, the URLs served by Eve have to be either absolute (`http://...`) or relative to the request URL (e.g. `/api/v1/...`), but _not_ to the entry point.

Therefore, I propose an **optional** setting that would make Eve’s HATEOAS conform to this expectation.

For example, this setting could take a form of a “base entry point URL” against which the current URLs are to be resolved. If the user specifies `/api/v1/`, then a URL like `people?page=2` would be transformed to `/api/v1/people?page=2`. If the user specifies `http://example.com/_myLegacyApp/`, then a URL like `people?page=2` would be transformed to `http://example.com/_myLegacyApp/people?page=2`.

Since this setting would be optional, installations that don’t know / don’t care about their location in the URL space can keep running with the current relative-to-entry-point URLs, which are better than nothing.

Alternatively, for installations where the gateway (if any) preserves the “real” request URL (i.e. `Host` and request path), maybe Eve could look at that to derive the “real” HATEOAS URLs, again triggered with an optional setting.

If you agree with the overall idea, I can give it a try.

**Comment by nicolaiarocci** [comment]
Hmm I like this, go for it!

**Comment by vfaronov** [comment]
Sorry, I haven’t got around to this yet. Hoping next week.

But I’ve thought some more about it, and it seems that we don’t need any complicated settings, because we can always reliably generate URIs that are relative to the request URI (like `../people?page=2`), regardless of any gateway trickery that may be going on. The only setting we need is a simple boolean switch to enable the new behavior.

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by nicolaiarocci** [comment]
Any news on this?

**Comment by nicolaiarocci** [comment]
Closing the ticket for the time being. Still open to an eventual PR.
