### ISSUE TITLE
geojson Point with mongodb

### ISSUE THREAD

**Issue by s3ppo** [nicolaiarocci/eve#819]
Hi!

I am trying to use the point type from geojson in my schema:

settings.py:
schema = {
    'location': {
        'type': 'point',
    }
}

request:
var oEntity = { location: {type: "Point", coordinates: [ 100.0, 10.0 ] } };

but when i send my request i get back:
{"_status": "ERR", "_issues": {"location[coordinates][]": "unknown field", "location[type]": "unknown field"}, "_error": {"message": "Insertion failure: 1 document(s) contain(s) error(s)", "code": 422}}

Best regards
Harald

**Comment by s3ppo** [comment]
when i try it from postman i get back:
{"_status": "ERR", "_issues": {"location": "Point not correct { \"type\": \"Point\", \"coordinates\": [ 776, 776 ] }: string indices must be integers"}, "_error": {"message": "Insertion failure: 1 document(s) contain(s) error(s)", "code": 422}}

**Comment by nicolaiarocci** [comment]
Have you tried with the [example](http://python-eve.org/features#geojson) in the docs? It is hard to tell since we don't get to see how your request is performed.

**Comment by nicolaiarocci** [comment]
Also, did you create the geoindex in the database? See https://stackoverflow.com/questions/32864091/geojson-python-eve-example/32871017#32871017

**Comment by s3ppo** [comment]
thank you its working now.. i think it was the index, but i am not sure :)
