### ISSUE TITLE
on_post hooks not triggered when by 500 responses

### ISSUE THREAD

**Issue by mcreenan** [nicolaiarocci/eve#822]
I have an on_post hook setup for each http method which logs information about the request and response to an external service.

For most requests, this works fine.

However, if I do a POST with resource that fails a unique constraint in mongo, Eve returns a 500 error like such:

```
   <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
   <title>500 Internal Server Error</title>
   <h1>Internal Server Error</h1>
   <p>pymongo.errors.OperationFailure: batch op errors occurred</p>
```

The on_post_POST hook I have is ignored.

It appears any time the abort method is used within Eve, it basically bombs out and any hooks that would normally execute will not be reached.

**Comment by nicolaiarocci** [comment]
That's right. Eve being a subclass of Flask, `abort` will return control to the caller (your launch script). `on_post` hook is invoked after the event has been successfully completed.

**Comment by mcreenan** [comment]
Ah ok.  Is there a recommended or known way to capture any 500 errors and modify them before they are sent back (similar to how we can with hooks)?

**Comment by nicolaiarocci** [comment]
Try with the following:

```py
@app.errorhandler(500)
def catch_server_errors(e):
    logging.exception("Something awful happened!")
```

**Comment by mcreenan** [comment]
Great, that worked.

Able to do `from flask import current_app, request as current_request` to get request and app information that would normally be available in the hook as well.

Thanks!
