### ISSUE TITLE
eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.

### ISSUE THREAD

**Issue by tigrus** [nicolaiarocci/eve#823]
When we do in settings.py something like: 
`raise Exception('Break!')`

Eve raises error `eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.`. 

This is really confusing, when you are starting working with framework. I think, it should raise error which really happened. 

Currently for me worked receipt from here: 
https://github.com/RedTurtle/eve-sqlalchemy/issues/15

But let's do something to see real error, which happened in settings.py.

https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L245 - here we must catch KeyError, not all Exceptions.

**Comment by nicolaiarocci** [comment]
On which Eve version are you? This should be already fixed on 0.6+.

**Comment by tigrus** [comment]
Oh. Sorry. was on 0.5.3
