### ISSUE TITLE
Access-Control-Allow-Max-Age is Access-Control-Max-Age

### ISSUE THREAD

**Issue by bustawin** [nicolaiarocci/eve#829]
With the latest stable version of Python-eve browsers do not cache OPTIONS. By just changing the header from Access-Control-Allow-Max-Age to Access-Control-Max-Age is solved.

From the specification:
https://www.w3.org/TR/2008/WD-access-control-20080912/#access-control-max-age

**Comment by nicolaiarocci** [comment]
Ah wow... thanks!

**Comment by nicolaiarocci** [comment]
Should be fixed now.
