### ISSUE TITLE
@app.route + auth

### ISSUE THREAD

**Issue by ddurieux** [nicolaiarocci/eve#832]
Hello, I have defined a token auth (class MyTokenAuth(TokenAuth)) and it works nice ;)

But (yes I have a problem :p) when I add a custom route (with @app.route()), auth is bypassed. 
How can I say to my app to check auth with this custom route?

Thanks ;)

**Comment by botzill** [comment]
Hi.

Maybe you can use [requires_auth](https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/get.py#L29) decorator as is currently used in the framework. Hope that helps.

**Comment by ddurieux** [comment]
Yes it works, thanks ;)

**Comment by nicolaiarocci** [comment]
Thanks @botzill !
