### ISSUE TITLE
schema data_relation to _id field failing

### ISSUE THREAD

**Issue by txomon** [nicolaiarocci/eve#834]
I don't know how to describe properly the problem, but I can say why is not working. Using pypi version (0.6.1). May be related to #733

I have a resource and a sub_resource. First, I create the resource with a PUT, because I have a microservice based architecture, and the main resource is always to be initialized in the new endpoint (usually the user) with specific data to the problem. In this case, the idea is to save data from the same user in different profiles, and display one or another based on its default selection.

I have put down a stripped version of the settings.py file.

The problem is that once I create a profile, which denotes basically the user's preference on the different options, I can create entries, but not retrieve them.

I have been exploring the problem, and the difference is that eve.io.mongo.mongo.Mongo.find() makes a call to `self._mongotize()` while eve.io.mongo.mongo.Mongo.insert() doesn't. Therefore, the entry in the database looks like:

```
{ "_id" : ObjectId("56e346bcedcc502535b80faf"), "type" : "preference_1", "value" : 50, "_updated" : ISODate("2016-03-11T22:25:53Z"), "_etag" : "3e2a5e7d2eabb2f075e9875da53e3b2ceef99344", "userid" : "56e05b2d8b8000a46d71baaa", "_created" : ISODate("2016-03-11T22:25:53Z") }
```

But the query looks like:

```
{'userid': ObjectId('56e05b2d8b8000a46d71baaa')}
```

Therefore returning 0 results.

So you will only be able to create documents but not retrieve them. Here an example:
```
selections = {
    'type': 'string',
    'allowed': [
        'preference_1',
        'preference_2',
    ]
}

profiles_schema = {
    'default': selections,
}

profiles = {
    'schema': profiles_schema,
    'resource_methods': ['GET'],
    'item_methods': ['PUT', 'GET', 'DELETE'],
}

entries_schema = {
    'userid': {
        'data_relation': {
            'resource': 'profiles',
            'field': '_id',
        }
    },
    'value': {'type': 'integer'},
    'ts': {'type': 'datetime'},
    'type': selections,
}

entries = {
    'schema': entries_schema,
    'resource_methods': ['GET', 'POST'],
    'item_methods': ['PUT', 'GET', 'DELETE'],
    'url': 'profiles/<regex("[a-f0-9]{24}"):userid>/entries',
}
```

**Comment by nicolaiarocci** [comment]
Hello, by looking at your snippet I can notice that what `userid` has no type definition. What happens if you set your `userid` field to a `objectid` type? My guess is that since it is missing type information it is assumed as a string, hence that weird behaviour.

**Comment by txomon** [comment]
Then the bug is in the find() function because it is generating it as ObjectId() when defined as string. I will be trying this now and report back

**Comment by txomon** [comment]
Yes, specifying the type for the referenced field works.

However IMO, `userid` should not have to specify the type. That is just a reference, and should always be inferred (maybe using self._mongotize()).

**Comment by nicolaiarocci** [comment]
> Explicit is better than implicit. - [Zen of Python](https://www.python.org/dev/peps/pep-0020/)

**Comment by txomon** [comment]
Following the quote method, it should fail if not declared. Accepting a
default that is broken does also go against the zen:

Errors should never pass silently
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.

=)
