### ISSUE TITLE
What is the reason to add additional fields (_created, _updated etc.) for each record?

### ISSUE THREAD

**Issue by istinspring** [nicolaiarocci/eve#836]
http://python-eve.org/features.html#projections as far as i understand i can not remove this fields from api response, but it does not make too much sense, what if i just connected my collection as a eve domain/endpoint and this automatically added fields are wrong and moreover require additional bandwidth?

Maybe there should be option to filter this fields from api response?

**Comment by nicolaiarocci** [comment]
You could  filter them out in a callback function, if you really don't want them in. Something like this:

```py
from eve import Eve

def on_fetched_resource(resource, response):
    for doc in response['_items']:
        for field in doc.keys():
            if field.startswith('_'):
                del(doc[field])

app = Eve()
app.on_fetched_resource += on_fetched_resource

if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by istinspring** [comment]
Thank you for response. Yea, i implemented like this but it's a bit "hacky" on my taste. What is the reason to always put a couple of fields on each response? There is plenty of situations when it does not make any sense.

**Comment by nicolaiarocci** [comment]
Well, consistency and robustness I guess. If you let `_updated` go you then can't do `If-Modified-Since` requests, and the lack of  `_etag` will prevent conditional requests (edits). Of course I recon that not all APIs might need/want this.

One thing we could experiment with, is allowing `ETAG`, `CREATED`, etc. to be set to null. When null, they are not added to response payloads.

**Comment by istinspring** [comment]
>  If you let _updated go you then can't do If-Modified-Since requests, and the lack of _etag will prevent conditional requests (edits). 

I added collection which is created through pymongo outside eve so there is no _created and _updated. Eve just insert this fields with Jan 01 1970 value.

**Comment by tanoabeleyra** [comment]
If anyone is in the same boat, this is how you can hide those fields from the response:
```python
def exclude_fields(resource, response):
    excluded_fields = ["_created", "_updated", "_etag"]
    for doc in response['_items']:
        fields = list(doc.keys())
        for field in fields:
            if field in excluded_fields:
                del(doc[field])


app = Eve()
app.on_fetched_resource += exclude_fields
```

@nicolaiarocci Those fields are really useful, but it would be nice to allow to hide them from the response to save bandwidth. In my particular case the client (app) doesn't need any of them, the API is read-only and the updated/created date isn't used. But I DO want to have them in the database just in case.

**Comment by shres707** [comment]
File "run.py", line 5, in on_fetched_resource
    for field in doc.keys():
RuntimeError: dictionary changed size during iteration
127.0.0.1 - - [07/Dec/2022 19:57:52] "GET /request_summary HTTP/1.1" 500 -

**Comment by shres707** [comment]
Hello All,
               Getting below error when tried on_fetched_resource () callback function as above
File "run.py", line 5, in on_fetched_resource
    for field in doc.keys():
RuntimeError: dictionary changed size during iteration
127.0.0.1 - - [07/Dec/2022 19:57:52] "GET /request_summary HTTP/1.1" 500 -
