### ISSUE TITLE
TokenAuth prevents base64 decoding of tokens

### ISSUE THREAD

**Issue by artburkart** [nicolaiarocci/eve#840]
Hi, I left a comment in the code [here](https://github.com/nicolaiarocci/eve/commit/24b30bc49dd8d5bb0017e8477910837bb218e802#diff-7303d4089a7f42fde94cc846a0c7d679R253).

> When I have a token that looks like `Authorization: token SGVsbG8=`, the a base64 decoder will give me `Hello`, but when `lower()` is applied to my token, I will get `²ìn`.
>
> To make TokenAuth work in my app, I override the `authorized` method and remove the `lower()` bit. I guess I'm wondering if this was the intended behavior?
>
> Cheers!

If it is the intended behavior, would it be okay if I made a PR to update the documentation to point out how to override the `authorized` method appropriately?

Thanks for this awesome project! :smile:

**Comment by nicolaiarocci** [comment]
Hello @artburkart. I actually saw your code comment but did not have the time look at it. See my answer there.
