### ISSUE TITLE
add user field to OPLOG

### ISSUE THREAD

**Issue by cbocta** [nicolaiarocci/eve#846]
I propose to create a new field identifying the author of the change for each resource of the OPLOG collection, this field could be the username of the author of the change. 

https://groups.google.com/forum/#!topic/python-eve/jIxoBA3MQC8

**Comment by einarhuseby** [comment]
I propose to be able to configure custom fields for OPLOG and a way of assigning values to those fields.

On a current project we are using ```OPLOG_CUSTOM_FIELDS = {'u': None, ..}``` then let the custom auth assign the current user id and other fields, updates the fields in oplog schema and sets the values in methods/common.py.   I'm not sure this is the best way, but works for our scenario.

**Comment by cbocta** [comment]
why not it could be more flexible than creating a dedicated author field....but it opens a door to make OPLOG collection quite big. 
@einarhuseby : maybe you can propose a PR?
@nicolaiarocci : what do you think?

**Comment by nicolaiarocci** [comment]
Right now I have a local branch which adds a pair of `set_user_or_token()`/`get_user_or_token()` methods to all basic auth classes. The set method is used internally whereas the get method is used by the oplog to grab the user and add it to the log when available. I might be able to merge it by the weekend (no promises though).

**Comment by cbocta** [comment]
Great! Tell us if you need some help!

**Comment by nicolaiarocci** [comment]
@cbocta it's live on develop branch
@einarhuseby working on it

**Comment by nicolaiarocci** [comment]
@einarhuseby done.

**Comment by einarhuseby** [comment]
@nicolaiarocci Thanks! I now realize that it was the missing event hooks on op_log that started it all on my side. Attaching event hooks to op_log is by far the best path.

**Comment by cbocta** [comment]
@nicolaiarocci I think event hookson OPLOG can be of great help, Thanks for your commits :-) !
