### ISSUE TITLE
Different MONGO_QUERY_BLACKLIST for GET vs POST

### ISSUE THREAD

**Issue by harryjubb** [nicolaiarocci/eve#847]
Is it possible, or could it be possible, to have a different `MONGO_QUERY_BLACKLIST` for different HTTP methods?

The main reason I ask is, I would like to be able to search using `$regex` for read only queries, without exposing any ability to alter the database by regex matching.

**Comment by nicolaiarocci** [comment]
`MONGO_QUERY_BLACKLIST` is only used on GET requests, no query parameters are parsed when other HTTP methods are used. I would say that you can whitelist `$regex` if you need it.

**Comment by harryjubb** [comment]
Thanks for your response, that's great to know :)

On Thu, 31 Mar 2016 at 06:55, Nicola Iarocci <notifications@github.com>
wrote:

> Closed #847 <https://github.com/nicolaiarocci/eve/issues/847>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaiarocci/eve/issues/847#event-609301860>
>
-- 
---

Harry Jubb
harry.jubb@gmail.com
