### ISSUE TITLE
Multiple databases problem needs help

### ISSUE THREAD

**Issue by zgs225** [nicolaiarocci/eve#848]
I’m a beginner of Python, and I’m using Python Eve in my project. Now, I have a problem which 
can’t find solution on Google, and I have to ask for help.

I need the Eve to work on Mysql and Mongo DB. Thus,

http://api.example.com/api/v1/users work on Mysql,
http://api.example.com/api/v1/logs  work on Mongo DB

What is the best way to achieve this with Eve?
Thanks for any advice,

**Comment by amleczko** [comment]
It's a very complex problem. The safest approach would be to have two eve applications running:
 * one that will handle mongodb
 * second for mysql
Then you can proxy request to proper endpoints using frontproxy like nginx or apache.

**Comment by zgs225** [comment]
Thanks lot for your answer.
