### ISSUE TITLE
API for publishing data analysis

### ISSUE THREAD

**Issue by hugo-pires** [nicolaiarocci/eve#852]
Hello
I want to use Eve to publish results, like averages, minimums and sums of a MongoDB meteorological dataset, calculated with aggregation framework.

Is it correct to call one of this functions a Resource?

Thank you

**Comment by nicolaiarocci** [comment]
Hello, the development branch has support for the Aggregation Framework. Check out the [documentation](http://python-eve.org/features#mongodb-aggregation-framework). Although it's not been released yet, you can use it already by cloning the repo.
