### ISSUE TITLE
ability to control count operation for get request on a resource

### ISSUE THREAD

**Issue by romanga** [nicolaiarocci/eve#853]
as you know count operation is very expensive, we can introduce another parameter that will tell eve to or not to perform cursor.count() operation:
GET /resource?count=0
something like the following:

> if config.DOMAIN[resource]['pagination'] and not \
>            ("count" in req.args and req.args["count"] == "0"):
>        count = cursor.count(with_limit_and_skip=False)
>    else:
>        count = len(documents)

**Comment by nicolaiarocci** [comment]
I assume you are not interested in pagination and/or HATEOAS, right? We might perform the count only if one of the two features is enabled for the endpoint. So you would turn pagination and HATEOAS off and you would get no count() operation with that.

**Comment by romanga** [comment]
that is one way, but then we'll need to define 2 separate endpoints for the same collection.
I'm sure there will be times when you'd want to dynamically control that and not just completely disable pagination for endpoint.
For example, you're using this query as subquery to another query, and not interested in total count, another one, you want to split result list query from pagination metadata query.

**Comment by nicolaiarocci** [comment]
That would lead to inconsistent responses from the endpoint (they may or may not include pagination/hateoas meta). Probably not a big deal since it is the client which requests the different payload, so we can assume it knows what it is doing. And we could add a server-side setting which allows to turn off this feature. Let me experiment with it a little bit.

**Comment by nicolaiarocci** [comment]
I'm working on a fix for this, see #944. Closing this one to reduce noise.
