### ISSUE TITLE
Broken Link in Docs

### ISSUE THREAD

**Issue by resolutedreamer** [nicolaiarocci/eve#861]
Hello Eve Team,

I'm reading the website at this URL
http://python-eve.org/install.html
and on the section titled "Distribute & Pip" there is a link that says "But, you really shouldn’t do that." that links to this URL
https://pip.pypa.io/en/latest/other-tools/#pip-compared-to-easy-install
which is not working.
The same issue is on the stable docs URL
http://eve.readthedocs.io/en/stable/install.html

Best,
Anthony Nguyen

**Comment by nicolaiarocci** [comment]
Thanks for reporting this. After the first iteration where I fixed the link, I then ended up removing the (now very obsolete) `easy_install` reference altogether.
