### ISSUE TITLE
Python-Eve query filter to find records in a range of values

### ISSUE THREAD

**Issue by stephen-talari** [nicolaiarocci/eve#863]
I am able to do `>` OR `<` operations individually as below

`example.com/api?where={"_id":">50"}`

But how can i query for _ids between two values like `_id>50` and `_id<100` ?

My DB postgresQL, not MongoDB

**Comment by s3ppo** [comment]
try something like:
example.com/api?where{"_id": {"$GT": "50", "$LT": "100"}}

LG :-)
Harald

**Comment by stephen-talari** [comment]
@s3ppo that didn't help.

**Comment by nicolaiarocci** [comment]
You should open this in the Eve-SQLAlchemy repo, Eve-core does not handle SQL natively I'm sorry.
