### ISSUE TITLE
Get mongodb collection using Eve 

### ISSUE THREAD

**Issue by andrecastro0o** [nicolaiarocci/eve#869]
I have mongod instances running on a server with a database on it.     
I'm trying to set up eve as REST http API to the database, for simple respond to GET requests.

If I request http://92.51.132.110:28017/clockrefdb/test/rows by using mongod REST Interface, I get:

    {
    "offset" : 0,
    "rows": [
    { "_id" : { "$oid" : "5745ef6494aef075d127f1d0" }, "timestamp" : { "$date" : "2016-05-25T22:31:00.035+0200" }, "frequencies" : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] } ,
    { "_id" : { "$oid" : "5747034194aef04e87df598d" }, "timestamp" : { "$date" : "2016-05-26T18:08:01.209+0200" }, "frequencies" : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] } ,
    { "_id" : { "$oid" : "5747050094aef04fe7aa7c14" }, "timestamp" : { "$date" : "2016-05-26T18:15:28.576+0200" }, "frequencies" : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] } ,
    { "_id" : { "$oid" : "5747050b94aef04ff397c81f" }, "timestamp" : { "$date" : "2016-05-26T18:15:39.779+0200" }, "frequencies" : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] } ,
    { "_id" : { "$oid" : "5747052694aef050096e5c71" }, "timestamp" : { "$date" : "2016-05-26T18:16:06.635+0200" }, "frequencies" : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] } ,
    { "_id" : { "$oid" : "57470a1694aef0536bf1d712" }, "timestamp" : { "$date" : "2016-05-26T18:37:10.022+0200" }, "frequencies" : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] }
    ],
    "total_rows" : 6 ,
    "query" : {} ,
    "millis" : 0
    }

Which are the correct values from the documents in the db. 
Now if I run eve and with settings:

    
    DOMAIN = { 'test':{} }                                               
    MONGO_HOST = 'localhost'
    MONGO_PORT = 27017
    MONGO_USERNAME = 'user'
    MONGO_PASSWORD = 'passw'
    MONGO_DBNAME = 'clockrefdb'
    RESOURCE_METHODS = ['GET']

And run eve with the default script:

    python run.py

And `curl --header "Accept:application/json" "http://127.0.0.1:5000/test/57470a1694aef0536bf1d712"`

I get:

    {
    "_created": "Thu, 01 Jan 1970 00:00:00 GMT", 
    "_etag": "c020b57efefeb92a74f5d07875d9234e3aef077a", 
    "_id": "57470a1694aef0536bf1d712", 
    "_links": {
        "collection": {
            "href": "test", 
            "title": "test"
        }, 
        "parent": {
            "href": "/", 
            "title": "home"
        }, 
        "self": {
            "href": "test/57470a1694aef0536bf1d712", 
            "title": "Test"
        }
    }, 
    "_updated": "Thu, 01 Jan 1970 00:00:00 GMT" }

Two things standout: the wrong date, and the missing table. 
What do you think is provoking this incorrect reading of the db?                     
I guess I am missing some important  steps.                                           
Any idea   which?

**Comment by nicolaiarocci** [comment]
Hello, see my answer on [Stack Overlow](https://stackoverflow.com/questions/37499746/get-mongodb-collection-using-eve/37510612#37510612), which is the right place for general usage questions.
