### ISSUE TITLE
0.6.4 release?

### ISSUE THREAD

**Issue by amorphic** [nicolaiarocci/eve#871]
Hi Nicola. Just wondering whether you have plans to release 0.6.4 in the near future? There are quite a few bugfix [changes](https://github.com/nicolaiarocci/eve/blob/develop/CHANGES) that I need for my current project. If possible I'd rather run an official package from PyPI on my prod servers than a github checkout of the dev branch. Cheers!

**Comment by nicolaiarocci** [comment]
Hello James. Once #872 is triaged and (eventually) fixed, I'm ready to release 0.6.4.

In short: Hopefully This Week™

**Comment by nicolaiarocci** [comment]
v0.6.4 is out in the wild.

**Comment by amorphic** [comment]
Fantastic news Nicola! Many thanks :smile:
