### ISSUE TITLE
404 on DELETE for URRA-enabled Endpoint when GET is public

### ISSUE THREAD

**Issue by kenmaca** [nicolaiarocci/eve#872]
I have an endpoint that is User-Restricted Resource Access enabled, but have `GET` for both the resource and item level public. `DELETE` however is a configured method, but not public. The config is as follows:

```
    'public_methods': ['GET'],
    'public_item_methods': ['GET'],
    'item_methods': ['GET', 'DELETE'],
    'resource_methods': ['GET', 'POST'],
```

I can `GET` with no issues, and it appears that URRA is working (401 when attempting to use `DELETE` or `POST` without authentication).. but `DELETE` after authentication results in a 404 for some reason.

**Comment by nicolaiarocci** [comment]
Hello, I am not able to not reproduce this. Just to make sure, did you include the item etag (via IF-MATCH header) with the DELETE request?

**Comment by kenmaca** [comment]
Thank you for the quick response!

It turns out that some of my hooks were doing funny things with the `lookup` causing the 404 code. I've removed these and it appears that Eve is working as designed. Sorry about that!
