### ISSUE TITLE
Cannot filter on datetime on the _updated field

### ISSUE THREAD

**Issue by stratosgear** [nicolaiarocci/eve#878]
For the life of me I cannot do a simple fitlering on the ``_updated`` field and retrieve documents that have been updated < one week ago.

For example:

    /jobs?where={"_updated": {"$lte":"Wed, 08 Jun 2016 10:29:13 GMT"}}

I get no results (although I have plenty documents).  Diferrent date formats, do **not** seem to help either.

A similar query through the mongodb shell (robomongo actually) **also** fails.  I can make it work (return results that is) only by wrapping the date in ISODATE, like:

    db.getCollection('jobs').find({"_updated": {"$lte":ISODate("2016-06-8 10:29:13.637Z")}})

and it works with a multitude of date formats inside ISODate.

I'm on Eve 0.6.4, mongodb 3.2.6 and I have not modified the default DATE_FORMAT (so I should be on the default RFC1123 format)

Any ideas on how to debug this?

**Comment by nicolaiarocci** [comment]
Hmm I just tested this and it works on my end. I am on Eve 0.6.4.dev0 with mongo 3.0.2. 

    GET /contatti/?where={"_updated": {"$lte": "Tue, 29 Mar 2016 09:52:28 GMT"}} HTTP/1.1
    Host: localhost:5000
    Content-Type: application/json
    Cache-Control: no-cache
    Postman-Token: ec21a218-7746-90ac-52b8-02ddbfb8b1d9


    {
        "_items": [
            {
                "_updated": "Wed, 16 Mar 2016 08:25:10 GMT",
                ...
              },
              {
                 "_updated": "Tue, 29 Mar 2016 09:52:28 GMT",
                 ..
               }

Etc.

**Comment by stratosgear** [comment]
Would you believe it that after rebooting today (for another reason) now it works...?

I must have spent more than two hours yesterday upgrading my stack (Eve, pymongo and mongodb) to your latest version and testing it out, and still it refused to work!

Quite embarrassingly, I apologize for wasting your time, I thank you for actually checking this out, and I'm closing this issue...

**Comment by nicolaiarocci** [comment]
No worries, I'm glad that you sorted it out.
