### ISSUE TITLE
XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by PenguinMe** [nicolaiarocci/eve#879]
Hi, I am doing some codes with **python-eve**. I got an issue.
In a **blog editor** page, I have a **textarea** to store **markdown style** string and the other **textarea** to store the **html tags style** string. Then post this two big long strings to the **mongodb** by **eve**. Then I find the blog list by API _http://127.0.0.1:8000/api/v1/blog_, it shows with error:**XML Parsing Error: not well-formed.**

![XML Parsing Error: not well-formed error](https://cloud.githubusercontent.com/assets/5775792/16388356/624591fe-3ccb-11e6-9b0e-c72ef63e7317.png)

I also use **Django** to find the blog list and it's fine to display on the html page.

I have tested for some codes and found below:
If I post the **markdown style** string, and with code, such as Linux vi code, 
```
#vi /root/.vnc/xstartup
```
 then I got the error.

**Comment by nicolaiarocci** [comment]
Could you post a dump of your eve response?

**Comment by PenguinMe** [comment]
@nicolaiarocci I am sorry, I test it some times again and found it's the **browser auto parse** error, not from the eve. Thanks for your attention, and hope it doesn't take up your time.
