### ISSUE TITLE
Search in list returns nothing

### ISSUE THREAD

**Issue by Rodrigocg** [nicolaiarocci/eve#880]
My query does not work in EVE only in shell mongo.

I have the following conguration:

company = {
    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'cnpj'
    },
    'schema': {
        'name': {
            'type': 'string',
            'required': True,
        },
        'endereco': {
            'type': 'string',
        },
        'cnpj': {
            'type': 'string',
            'required': True,
        },
        'files': {
            'type': 'list',
            'schema': {
                'type': 'string',
            }
        },
    }
}

and the search:
http://127.0.0.1:5000/company?where={"files":{"$in" : ["57745a3cae48402aba87c80a"]}}

My search had to return a document, but returns:

{
  "_meta": {
    "total": 0,
    "max_results": 25,
    "page": 1
  },
  "_links": {
    "self": {
      "href": "company",
      "title": "company"
    },
    "parent": {
      "href": "/",
      "title": "home"
    }
  },
  "_items": []
}

**Comment by nicolaiarocci** [comment]
Your `files` values are strings, but they look like objectids to Eve. Try setting `query_objectid_as_string` to `True` for the resource.

**Comment by Rodrigocg** [comment]
Thanks, worked perfectly.
