### ISSUE TITLE
additional_lookup by subdocument field is not supported

### ISSUE THREAD

**Issue by bofm** [nicolaiarocci/eve#886]
Document example:
```
{
    ...
    "_id": ObjectId("579241a6d066a41daec945ca"),
    "metadata": {
        "item_id": 123456,
        ...
    }
...
}
```

`'additional_lookup': {'field': 'metadata.item_id'}` causes EVE to fail as it restricts dotted fields declaration (#780).

**Comment by nicolaiarocci** [comment]
Yes this is not supported. To my  knowledge, Werkzeug/Flask will not accept a dotted variable into `add_url_rule()`, returning 'malformed url rule'.

**Comment by talatbaig** [comment]
Filtering on embedded document fields is possible so why is this not possible?

def pre_GET(resource, request, lookup):
    lookup["article.type"] = 'news'
