### ISSUE TITLE
Docs are not clear about installation requirements

### ISSUE THREAD

**Issue by mloskot** [nicolaiarocci/eve#889]
The docs say:

> Eve is powered by Flask, Redis, Cerberus, Events

but it does not indicate if all of those are required.

Specifically, I have failed to find anywhere in the docs if Redis is an optional dependency.

Looking into the requirements.txt and reading usage samples of Redis, `app = Eve()`  vs `app = Eve(redis=r)` also suggests Redis is optional.

However, that is too many hoops for those new to Eve to conclude about Redis requirement - many may give up having no option to host Redis. For example, PythonAnywhere users: [I couldn't tell from their docs whether redis is a hard requirement or something that you can use for some features](https://www.pythonanywhere.com/forums/topic/3730/#id_post_18968)).

**Comment by nicolaiarocci** [comment]
Good point! We should probably remote it from the list, or add a note that it is currently only required when the rate-limiting feature is enabled. Care to submit a PR?

**Comment by mloskot** [comment]
@nicolaiarocci  I think there is no need to remove Redis from the sentence. I proposed trivial change in #892 that should make the requirements clearer.
