### ISSUE TITLE
Clarify how to do "or" filter in mongo format

### ISSUE THREAD

**Issue by jakul** [nicolaiarocci/eve#895]
Hiya,

I've found the documentation on filtering is a bit sparse. I'm trying to work out how to do "or" filtering using the mongo syntax, but I can't work it out!

I want to update the documentation with an example, I just can't work out how to do the filtering!

For reference, I have these (working) filters at the moment:

```
?where=scope=="group"%20and%20scope_id=="21905251-1fa2-42c8-81b5-43abc06ede5a"'
?where=scope=="provider"%20or%20scope_id=="21905251-1fa2-42c8-81b5-43abc06ede5a"'

?where={"scope":"group","scope_id":"21905251-1fa2-42c8-81b5-43abc06ede5a"}
```

**Comment by xgvargas** [comment]
Here we filter by name equal to 'barbosa' OR cost less then 30.
```
?where={$or: [{name: {$eq: "barbosa"}}, {cost: {$lt: 30}}]}
```
you can check [here](https://docs.mongodb.com/manual/reference/operator/query/) the syntax for other filters acepted by mongodb.
