### ISSUE TITLE
PendingDeprecationWarning from Flask

### ISSUE THREAD

**Issue by jakul** [nicolaiarocci/eve#898]
Hiya,

When I run my server I see this warning:

```
/Users/craig/.virtualenvs/service-intel/lib/python2.7/site-packages/flask/exthook.py:70: ExtDeprecationWarning: Importing flask.ext.pymongo is deprecated, use flask_pymongo instead.
```

Using Python==2.7.10, Flask==0.11.1, Eve==0.6.4

**Comment by glestaris** [comment]
I am happy to PR a fix but I got confused. it looks like Flask-PyMongo is already a dependency and in their docs [1], they mention the import path as `flask.ext.pymongo` which is the same that is currently giving us the deprecation warning.

[1] https://flask-pymongo.readthedocs.io/en/latest/

**Comment by jakul** [comment]
I think it's a change in how Flask works with extensions, not Flask-Pymongo specifically. 

https://github.com/pallets/flask/issues/1135

**Comment by glestaris** [comment]
Thanks @jakul that explains it! I will make a PR. Sounds simple enough :)
