### ISSUE TITLE
Any suggestion on integrating tornado with eve?

### ISSUE THREAD

**Issue by tonyshare** [nicolaiarocci/eve#913]
I am using `tornado` as my web server, and using `nginx` as its proxy. The database is `mariadb`, when i write the code that request data from `mariadb`, i want to use `eve` to integrate `mariadb` and `tornado` server, could you give me some advice. thanks!!

**Comment by nicolaiarocci** [comment]
Tornado has been kind of 'deprecated' as a Flask/Eve server, see [here](https://github.com/pallets/flask/pull/1187) where (by looking at the removed code snippet) you can also learn how to use with Flask. On mariadb, you should probably check with the eve-sqlalchemy folks.

**Comment by tonyshare** [comment]
thanks for your help, God bless you again!
