### ISSUE TITLE
DOMAIN dictionary missing or wrong with gunicorn

### ISSUE THREAD

**Issue by amoxyc** [nicolaiarocci/eve#918]
Hello!

Everything works fine on Heroku with Procfile 
`web: python run.py`

But when I switch to gunicorn, exception appears:

>  [2016-09-27 19:27:21 +0000] [9] [ERROR] Exception in worker process
> 2016-09-27T19:27:21.633227+00:00 app[web.1]: Traceback (most recent call last):
> 2016-09-27T19:27:21.633228+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
> 2016-09-27T19:27:21.633229+00:00 app[web.1]:     worker.init_process()
> 2016-09-27T19:27:21.633229+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
> 2016-09-27T19:27:21.633230+00:00 app[web.1]:     self.load_wsgi()
> 2016-09-27T19:27:21.633231+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
> 2016-09-27T19:27:21.633232+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
> 2016-09-27T19:27:21.633232+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
> 2016-09-27T19:27:21.633233+00:00 app[web.1]:     self.callable = self.load()
> 2016-09-27T19:27:21.633234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
> 2016-09-27T19:27:21.633235+00:00 app[web.1]:     return self.load_wsgiapp()
> 2016-09-27T19:27:21.633235+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
> 2016-09-27T19:27:21.633236+00:00 app[web.1]:     return util.import_app(self.app_uri)
> 2016-09-27T19:27:21.633237+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
> 2016-09-27T19:27:21.633238+00:00 app[web.1]:     **import**(module)
> 2016-09-27T19:27:21.633238+00:00 app[web.1]:   File "/app/run.py", line 28, in <module>
> 2016-09-27T19:27:21.633239+00:00 app[web.1]:     app = Eve()
> 2016-09-27T19:27:21.633240+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/eve/flaskapp.py", line 139, in **init**
> 2016-09-27T19:27:21.633240+00:00 app[web.1]:     self.validate_domain_struct()
> 2016-09-27T19:27:21.633241+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/eve/flaskapp.py", line 252, in validate_domain_struct
> 2016-09-27T19:27:21.633242+00:00 app[web.1]:     raise ConfigException('DOMAIN dictionary missing or wrong.')
> 2016-09-27T19:27:21.633243+00:00 app[web.1]: ConfigException: DOMAIN dictionary missing or wrong.

**Comment by nicolaiarocci** [comment]
On which Eve version are you? This usually means a misconfiguration.

**Comment by amoxyc** [comment]
Eve==0.6.4

**Comment by pollitux** [comment]
I have the same problem when trying to start my app with gunicorn

> python wsgi.py it works

> gunicorn -b 0.0.0.0:5000 wsgi:app not found 

`flaskapp.py", line 246, in validate_domain_struct
    domain = self.config['DOMAIN']
KeyError: 'DOMAIN'
`

**Comment by nicolaiarocci** [comment]
Hello folks, see if [this](https://groups.google.com/forum/#!topic/python-eve/TLKhBfT3H3o) thread helps (last message).

**Comment by harryjubb** [comment]
I still have this issue, using `--chdir` (`--chwd` isn't an option) doesn't help.

**Comment by ydaniels** [comment]
Yea any solution currently facing this problem

**Comment by nicolaiarocci** [comment]
Folks, I'm going to close this as it seems related to usage problems (see @ydaniels comment).
