### ISSUE TITLE
use $or to filtering one field 

### ISSUE THREAD

**Issue by janreyho** [nicolaiarocci/eve#929]
in the mongo shell `db.users.find({$or:[{"username":"tom"},{"username":"jan"}]})` filtering one field work.

how to use eve api to do this.`http://127.0.0.1:5000/bluapi/v1/users?where={$or:[{"username":"tom"},{"username":"jan"}]}` can't work

**Comment by petrjasek** [comment]
it should work, but you have to use urlencode:
```
http://127.0.0.1:5000/bluapi/v1/users?where=%7B%24or%3A%5B%7B%22username%22%3A%22tom%22%7D%2C%7B%22username%22%3A%22jan%22%7D%5D%7D
```
btw you can use `$in`: `{"username":{"$in":["tom", "jan"]}}`

**Comment by janreyho** [comment]
@petrjasek what is the ulr when is uncoded.

**Comment by petrjasek** [comment]
uncoded: `{$or:[{"username":"tom"},{"username":"jan"}]}`
encoded: `%7B%24or%3A%5B%7B%22username%22%3A%22tom%22%7D%2C%7B%22username%22%3A%22jan%22%7D%5D%7D`
you can check on http://meyerweb.com/eric/tools/dencoder/

**Comment by janreyho** [comment]
@petrjasek the url still can't work in chrome, and return
```
{
_error: {
code: 400,
message: "Unable to parse `where` clause"
},
_status: "ERR"
}
```

**Comment by janreyho** [comment]
@petrjasek I get it, In chrome omnibox, the $or must be "$or". thanks.
