### ISSUE TITLE
Lists of media

### ISSUE THREAD

**Issue by Leonidaz0r** [nicolaiarocci/eve#932]
Currently it seems to be impossible to have lists of media.

Suppose we have the following resource:

```
DOMAIN = {
        'some_resource': {
            'field1': {
                'type': 'list',
                'schema': {
                    'type': 'media'
                }
            }
        }
    }
```

This is a valid cerberus schema and will work fine. However there is no way to post to this. Eve does not even consider media fields somewhere else than on the top layer of the schema definition (https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L615).

As it would be handy to work with lists of files, I would propose the following addition to eve:
- If multiple fields are included in a request with the same key, collapse them into a list
- If the type is specified to 'list' in the schema and a non array is posted to that field, make it a one element array.

That way for example HTML forms with multiple file input elements for the same key would work. Something like this:

```
<p> Choose three files to upload:</p>
<input type="file" name="field1" />
<input type="file" name="field1" />
<input type="file" name="field1" />
```

One could also make a config flag to enable this behaviour (like AUTO_COLLAPSE_LISTS).
If this would be considered a feature, I might try to come up with an implementation.

**Comment by nicolaiarocci** [comment]
This has been addressed with #933
