### ISSUE TITLE
I there a way to avoid count operation with pagination enabled?

### ISSUE THREAD

**Issue by dvddarias** [nicolaiarocci/eve#944]
In MongoDB, a count operation on a query with a filter is very, very slow even with an index on the filtered fields. I would like to be able to disable the "_meta.total" calculation but still keep the pagination enabled.

I know I wont be able to calculate the total amount of pages but I prefer this instead of having to wait  ~10s per request just because of the count operation takes ~9.870s. : (

Is there any workaround to accomplish this??

**Comment by nicolaiarocci** [comment]
This could be solved with a new setting, say `PERFORM_COUNT_ON_PAGINATION`, enabled by default. If disabled, `next` and `prev` pagination links would still work but you would not be given a `last` page link. Sounds reasonable?

**Comment by nicolaiarocci** [comment]
More detail:

When `PERFORM_COUNT` is `False`:
- `X-Total-Count` header is missing
- `_meta.total` is missing
- `last` pagination link is missing
- `next` and `previous` links are still returned

**Comment by nicolaiarocci** [comment]
Maybe `OPTIMIZE_PAGINATION_FOR_SPEED` gives a better hint.

**Comment by dvddarias** [comment]
Sounds perfect!!!, in my particular use case the name: PERFORM_COUNT_ON_PAGINATION gives a better hint of what the configuration setting is doing. 
I think the name OPTIMIZE_PAGINATION_FOR_SPEED is not explicit enough and may loose significance if/when MongoDB team optimizes the count on indexed fields.

**Comment by nicolaiarocci** [comment]
I pushed a [new branch](https://github.com/nicolaiarocci/eve/tree/OPTIMIZE_PAGINATION_FOR_SPEED) with a possible implementation (WIP). Would you test it on your environment and report back on performance gain and eventual issues?

**Comment by nicolaiarocci** [comment]
@dvddarias did you manage to test that branch yet?

**Comment by dvddarias** [comment]
Yes, just did it, it correctly avoids any count operation when OPTIMIZE_PAGINATION_FOR_SPEED is set. Now the response time of the API is 134ms instead of 8secs in my particular case (collection with 900K entries)

**Comment by nicolaiarocci** [comment]
Awesome.

**Comment by nicolaiarocci** [comment]
ok it's on v0.7 now
