### ISSUE TITLE
Serializer for boolean

### ISSUE THREAD

**Issue by Leonidaz0r** [nicolaiarocci/eve#947]
If I use a field, where the type is "integer", I can also post a string containing an integer and it will be converted by the serializer.
Is there a reason this does not happen for booleans?
It is missing in this list:

https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/mongo.py#L77

**Comment by NotSpecial** [comment]
I have added a boolean serializer (#948)

It might be a bit much for one line, but I tried to keep it similar to the other serializers. But if you think it's helpful I could put it in a dedicated function, just let me know.

What it does is rather simple: A dict with '0', '1', 'true', 'false' as keys and respective booleans as values is created. Then we use str(val).lower() as a key for this dict.

Conversion to str makes sure we accept both 0 and '0' (same for 1). Conversion to lower takes care of 'false' vs 'False'.

If the value doesn't match a KeyError is thrown which will be caught by `serialize_value` so we should be fine.

What do you think?
