### ISSUE TITLE
filtering on embedded resource

### ISSUE THREAD

**Issue by ankur777** [nicolaiarocci/eve#956]
Is there any way to filtering on embedded resource

v1/claim?embedded={"cover_id":1,"cover_id.property_id":1}

Now I want to query on 

v1/claim?where={"cover_id.property_id.address.city":%20"capestown"}

Schema under cover_id is

property_id": {
"_updated": "Mon, 02 Jan 2017 11:47:12 GMT",
"_created": "Mon, 02 Jan 2017 11:47:12 GMT",
"owner_id": "586a3b7eb6fe8765c782b81a",
"_id": "586a3dc0b6fe8765c782b81b",
"images": [
"http://www.taxibrousse.org/wp-content/uploads/2015/09/TownshipPhoto.jpg",
"https://upload.wikimedia.org/wikipedia/commons/6/67/Vietnam_08_-_151_-_houses_over_the_canals_(3186477231).jpg",
"http://images.adsttc.com/media/images/5327/0f59/c07a/8042/fc00/024a/large_jpg/2013_12_15__CapeTown_00030-3.jpg?1395068740"
],
"area": 500,
"_etag": "c0adaf0e1991e1941a872de559ae3d974bccae7b",
"address": {
"country": "south africa",
"postal_code": "6628",
"municipality": "xyz a",
"city": "capestown",
"location": {
"coordinates": [
23.145355,
-33.724168
],
"type": "Point"

**Comment by nicolaiarocci** [comment]
You could probably achieve that by resorting to a [Aggregation endpoint](http://python-eve.org/features.html#mongodb-aggregation-framework). That's supported with v0.7, which is about to be released (you can already use it from github). 

The way I would do it is probably create a new, read-only, aggregation framework supported endpoint.

**Comment by pointtoken** [comment]
Did you ever solve this? I want to use eve to filter on embedded resources.
