### ISSUE TITLE
Question: Mutator like feature for fields in schema

### ISSUE THREAD

**Issue by sushilkjaiswar** [nicolaiarocci/eve#969]
I was thinking if we can have a support of mutators defined per field in eve schema which can modify those fields before inserting in db and after fetching it.

Use case: 
Storing respective field as encrypted in database and then retrieve and decrypt them at client side. e.g. would be personal info of users, or credential storage for third party softwares

I am aware of hooks currently to achieve the same but I think this feature would make much more sense as a part of eve framework.

Let me know what you think about this feature.

Thanks for this wonder full framework. its just awesome!!!

**Comment by nicolaiarocci** [comment]
This should be achievable with value coercion, which is allowed with Cerberus 0.9+. Take a look at the [docs](http://docs.python-cerberus.org/en/stable/normalization-rules.html#value-coercion)

**Comment by sushilkjaiswar** [comment]
Thanks.  I was looking for this.
