### ISSUE TITLE
Thoughts on X_DOMAINS regex support

### ISSUE THREAD

**Issue by membranepotential** [nicolaiarocci/eve#974]
Hi,

I wanted to share my thoughts on the regex support feature, because in its current form, it adds some surprise.

Because re.escape is used to parse the regex, the typical regex syntax doesnt work. For example, I my origin is http://localhost:8002 (for development). If I want to add the port range 8000-8009 for example, I expected `X_DOMAINS = ['http://localhost:800\d']` would work. But re.escape will change that to `'http\\:\\/\\/localhost\\:800\\\\d'`, so effectively the domain that is allowed is `'http://localhost:800\d'`.

On the other hand, `X_DOMAINS = ['http://localhost:800']` will also match `http://localhost:8002x`, because partial matches are allowed. So while it works for me in that respect, it adds origins that are not explicitly defined in the config.

I don't know if this has any consequences "in the real world", but I still wanted to draw your attention to it.

Cheers

#660

**Comment by nicolaiarocci** [comment]
Hello, thanks for sharing your thoughts. 

- What do you suggest as an alternative approach/fix? 
- Would you be willing to propose a PR?

**Comment by membranepotential** [comment]
I would suggest using a configuration flag that sets regex domains explicitly and leave the escaping and anchoring of the regex to the admin. That way it is clear which domains and domain ranges are whitelisted while the admin still has full control over the configuration.

E.g.
```python
'X_DOMAINS'=['http://www.example.com']
'X_DOMAINS_RE'=['^http://sub-\d{6}\.example\.com$']
```

I can send a PR if this approach is acceptable.

Another way would be to implement some sort of regex detection [(Flask-Cors does this)](https://github.com/corydolphin/flask-cors/blob/96c3ac7b8a2c7f6837c384e59d9a23283397385b/flask_cors/core.py#L245) This would avoid 2 X_DOMAINS settings, but I would prefer the explicit way.

Cheers

**Comment by nicolaiarocci** [comment]
I like this approach. If you could send a PR I'd merge it before 0.7 release, which is imminent. Thanks!

**Comment by nicolaiarocci** [comment]
This has been implemented. See PR #975
