### ISSUE TITLE
Can't access get_internal method.

### ISSUE THREAD

**Issue by feluxe** [nicolaiarocci/eve#976]
I need to make an internal mongodb call from within the eve-app (v0.6.4) to get info about the last entry.  I [read](http://stackoverflow.com/a/25324268/1612318) that you can use the `_internal` methods for this:

> Update: v0.5 has been released with _internal methods available for all CRUD operations.

So I  was trying `from eve.methods.get import get_internal` to but it's not available. I can't find it in the `methods.get` module at all.  How can I get access to the `get_internal` method? I'm a little confused.

**Comment by naskoos** [comment]
@feluxe I also have the same problem, instead I'm using the Flask's test_client() function. 
There is a branch in the repository called "get_internal" but I haven't tried it. 
I suspect that "get_internal" functionality is not yet added to the stable or the development branch, but lets hear what Nicola has to say about that issue.

**Comment by nicolaiarocci** [comment]
`get_internal` is only available in v0.7 which is going to be released Soon™ (see che [changelog](https://github.com/nicolaiarocci/eve/blob/develop/CHANGES))
