### ISSUE TITLE
Removal of develop branch

### ISSUE THREAD

**Issue by dkellner** [nicolaiarocci/eve#982]
@nicolaiarocci As stated in some PRs, you've deleted the `develop` branch recently. Can you explain the reason behind this decision? We have a discussion about our development and branching workflow at Eve-SQLAlchemy (https://github.com/RedTurtle/eve-sqlalchemy/issues/132) and I'm quite interested in your opinion here.

**Comment by nicolaiarocci** [comment]
Sure. Originally I've been loosely following the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) model. Over time I found that it to be too complicated, especially so when dealing with long-running branches. In all my other projects (public and private) I am using a [github-flow](https://help.github.com/articles/github-flow/)-like approach with success. Simpler, faster, easier to understand for unexperienced contributors. There are some differences though, for example I'm only releasing from master, not from feature branches as suggested in the linked resources. So I guess something from the git-flow is still haunting these halls :)
