### ISSUE TITLE
200 not 204 after DELETION

### ISSUE THREAD

**Issue by PaulDepraz** [nicolaiarocci/eve#987]
Is it compliance to answer 204 after successful deletion? I believe 200 would be even easier for generic handlers.

**Comment by nicolaiarocci** [comment]
> 9.7 DELETE
> A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.

Source : http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

I would say 204 is good since Eve does not provide any content with the body.

**Comment by pedro2555** [comment]
I would like to open this again.

I don't think returning 204 is ok with HATEOAS enabled; and I'm having trouble with it.

It would be very helpful if someone can clear my mind in here, but from a HATEOAS client's perspective a 204 response as no context associated with it, therefore violating the protocol.

It is ambiguous what to do, I figure we can:

1. Go back to the previous endpoint visited

2. Go the API entrypoint

3. Quit

Neither is particularly helpful, the most appropriate response at this point is actually to quit. There are no links to follow therefore the application must be state is 'finished'.

I hope I'm not overlooking a simple solution, but I can't really get my head around this issue.

**Comment by pedro2555** [comment]
And btw, this ain't an issue with DELETE requests alone. It is the 204 response that is the issue.
