### ISSUE TITLE
Quickstart Fails

### ISSUE THREAD

**Issue by nixphix** [nicolaiarocci/eve#988]
I tried to run the quick start app (http://python-eve.org/quickstart) but it tries to connect to mongo and fails with a connection exception.

eve.io.base.ConnectionException: Error initializing the driver. Make sure the database serveris running. Driver exception: ConnectionFailure('[Errno 111] Connection refused',)

**Comment by nicolaiarocci** [comment]
Make sure your mongo server is running and you are connecting on the right port. Also make sure user/pw to the db are correct.
