### ISSUE TITLE
Inconsistency of methods' error handling

### ISSUE THREAD

**Issue by lachaib** [nicolaiarocci/eve#994]
Hello,

I've noticed that in post.py, validation errors result in putting them in doc_issues["validation exception"]
while in patch.py and put.py, it is set in doc_issues["validator exception"]
I don't know if this behaviour is expected, but consistency would help when we want to have a specific error handler to reformat errors before replying.

Thanks

**Comment by nicolaiarocci** [comment]
Thanks. I agree, this is a bug and should be fixed.

**Comment by lachaib** [comment]
Thanks a lot!
